import type {
  TransactionIconDefinition,
  TransactionIconKey,
} from "./transaction-icon.types";

export const TRANSACTION_ICON_CATALOG = [
  {
    key: "accounting",
    path: "/transaction-icons/professional/accounting.svg",
    category: "PROFESSIONAL",
    label: "Accounting",
    aliases: ["accounting"],
    keywords: ["professional","accounting"],
  },
  {
    key: "agriculture",
    path: "/transaction-icons/agriculture/agriculture.svg",
    category: "AGRICULTURE",
    label: "Agriculture",
    aliases: ["agriculture"],
    keywords: ["agriculture"],
  },
  {
    key: "airtime",
    path: "/transaction-icons/utilities/airtime.svg",
    category: "UTILITIES",
    label: "Airtime",
    aliases: ["airtime","mobile recharge"],
    keywords: ["utilities","airtime","mobile recharge"],
  },
  {
    key: "allowance",
    path: "/transaction-icons/community/allowance.svg",
    category: "COMMUNITY",
    label: "Allowance",
    aliases: ["allowance"],
    keywords: ["community","allowance"],
  },
  {
    key: "appliances",
    path: "/transaction-icons/home/appliances.svg",
    category: "HOME",
    label: "Appliances",
    aliases: ["appliances"],
    keywords: ["home","appliances"],
  },
  {
    key: "bakery",
    path: "/transaction-icons/food/bakery.svg",
    category: "FOOD",
    label: "Bakery",
    aliases: ["bakery"],
    keywords: ["food","bakery"],
  },
  {
    key: "bank-fee",
    path: "/transaction-icons/finance/bank-fee.svg",
    category: "FINANCE",
    label: "Bank Fee",
    aliases: ["bank-fee","bank fee"],
    keywords: ["finance","bank","fee","bank-fee","bank fee"],
  },
  {
    key: "bar",
    path: "/transaction-icons/food/bar.svg",
    category: "FOOD",
    label: "Bar",
    aliases: ["bar"],
    keywords: ["food","bar"],
  },
  {
    key: "beauty",
    path: "/transaction-icons/shopping/beauty.svg",
    category: "SHOPPING",
    label: "Beauty",
    aliases: ["beauty"],
    keywords: ["shopping","beauty"],
  },
  {
    key: "bicycle",
    path: "/transaction-icons/transport/bicycle.svg",
    category: "TRANSPORT",
    label: "Bicycle",
    aliases: ["bicycle"],
    keywords: ["transport","bicycle"],
  },
  {
    key: "books",
    path: "/transaction-icons/education/books.svg",
    category: "EDUCATION",
    label: "Books",
    aliases: ["books","bookstore"],
    keywords: ["education","books","bookstore"],
  },
  {
    key: "books-digital",
    path: "/transaction-icons/digital/books-digital.svg",
    category: "DIGITAL",
    label: "Books Digital",
    aliases: ["books-digital","books digital"],
    keywords: ["digital","books","books-digital","books digital"],
  },
  {
    key: "bus",
    path: "/transaction-icons/transport/bus.svg",
    category: "TRANSPORT",
    label: "Bus",
    aliases: ["bus"],
    keywords: ["transport","bus"],
  },
  {
    key: "business-income",
    path: "/transaction-icons/income/business-income.svg",
    category: "INCOME",
    label: "Business Income",
    aliases: ["business-income","business income"],
    keywords: ["income","business","business-income","business income"],
  },
  {
    key: "business-services",
    path: "/transaction-icons/professional/business-services.svg",
    category: "PROFESSIONAL",
    label: "Business Services",
    aliases: ["business-services","business services"],
    keywords: ["professional","business","services","business-services","business services"],
  },
  {
    key: "butcher",
    path: "/transaction-icons/food/butcher.svg",
    category: "FOOD",
    label: "Butcher",
    aliases: ["butcher"],
    keywords: ["food","butcher"],
  },
  {
    key: "cable-broadband",
    path: "/transaction-icons/utilities/cable-broadband.svg",
    category: "UTILITIES",
    label: "Cable Broadband",
    aliases: ["cable-broadband","cable broadband"],
    keywords: ["utilities","cable","broadband","cable-broadband","cable broadband"],
  },
  {
    key: "cafe",
    path: "/transaction-icons/food/cafe.svg",
    category: "FOOD",
    label: "Cafe",
    aliases: ["cafe","coffee shop"],
    keywords: ["food","cafe","coffee shop"],
  },
  {
    key: "camera",
    path: "/transaction-icons/electronics/camera.svg",
    category: "ELECTRONICS",
    label: "Camera",
    aliases: ["camera"],
    keywords: ["electronics","camera"],
  },
  {
    key: "car-rental",
    path: "/transaction-icons/travel/car-rental.svg",
    category: "TRAVEL",
    label: "Car Rental",
    aliases: ["car-rental","car rental"],
    keywords: ["travel","car","rental","car-rental","car rental"],
  },
  {
    key: "car-repair",
    path: "/transaction-icons/transport/car-repair.svg",
    category: "TRANSPORT",
    label: "Car Repair",
    aliases: ["car repair","mechanic","garage","car-repair"],
    keywords: ["transport","car","repair","car repair","mechanic","garage","car-repair"],
  },
  {
    key: "car-wash",
    path: "/transaction-icons/transport/car-wash.svg",
    category: "TRANSPORT",
    label: "Car Wash",
    aliases: ["car-wash","car wash"],
    keywords: ["transport","car","wash","car-wash","car wash"],
  },
  {
    key: "cash-deposit",
    path: "/transaction-icons/finance/cash-deposit.svg",
    category: "FINANCE",
    label: "Cash Deposit",
    aliases: ["cash deposit","cash-deposit"],
    keywords: ["finance","cash","deposit","cash deposit","cash-deposit"],
  },
  {
    key: "cash-withdrawal",
    path: "/transaction-icons/finance/cash-withdrawal.svg",
    category: "FINANCE",
    label: "Cash Withdrawal",
    aliases: ["cash withdrawal","atm","cash-withdrawal"],
    keywords: ["finance","cash","withdrawal","cash withdrawal","atm","cash-withdrawal"],
  },
  {
    key: "cashback",
    path: "/transaction-icons/income/cashback.svg",
    category: "INCOME",
    label: "Cashback",
    aliases: ["cashback"],
    keywords: ["income","cashback"],
  },
  {
    key: "charity",
    path: "/transaction-icons/community/charity.svg",
    category: "COMMUNITY",
    label: "Charity",
    aliases: ["charity"],
    keywords: ["community","charity"],
  },
  {
    key: "childcare",
    path: "/transaction-icons/education/childcare.svg",
    category: "EDUCATION",
    label: "Childcare",
    aliases: ["childcare"],
    keywords: ["education","childcare"],
  },
  {
    key: "cleaning",
    path: "/transaction-icons/home/cleaning.svg",
    category: "HOME",
    label: "Cleaning",
    aliases: ["cleaning"],
    keywords: ["home","cleaning"],
  },
  {
    key: "clothing",
    path: "/transaction-icons/shopping/clothing.svg",
    category: "SHOPPING",
    label: "Clothing",
    aliases: ["clothing","apparel"],
    keywords: ["shopping","clothing","apparel"],
  },
  {
    key: "cloud",
    path: "/transaction-icons/digital/cloud.svg",
    category: "DIGITAL",
    label: "Cloud",
    aliases: ["cloud"],
    keywords: ["digital","cloud"],
  },
  {
    key: "community-support",
    path: "/transaction-icons/community/community-support.svg",
    category: "COMMUNITY",
    label: "Community Support",
    aliases: ["community-support","community support"],
    keywords: ["community","support","community-support","community support"],
  },
  {
    key: "computer",
    path: "/transaction-icons/electronics/computer.svg",
    category: "ELECTRONICS",
    label: "Computer",
    aliases: ["computer"],
    keywords: ["electronics","computer"],
  },
  {
    key: "consulting",
    path: "/transaction-icons/professional/consulting.svg",
    category: "PROFESSIONAL",
    label: "Consulting",
    aliases: ["consulting"],
    keywords: ["professional","consulting"],
  },
  {
    key: "convenience-store",
    path: "/transaction-icons/food/convenience-store.svg",
    category: "FOOD",
    label: "Convenience Store",
    aliases: ["convenience store","corner store","minimart","convenience-store"],
    keywords: ["food","convenience","store","convenience store","corner store","minimart","convenience-store"],
  },
  {
    key: "cooking-gas",
    path: "/transaction-icons/home/cooking-gas.svg",
    category: "HOME",
    label: "Cooking Gas",
    aliases: ["cooking gas","lpg","cooking-gas"],
    keywords: ["home","cooking","gas","cooking gas","lpg","cooking-gas"],
  },
  {
    key: "cooperative-savings",
    path: "/transaction-icons/finance/cooperative-savings.svg",
    category: "FINANCE",
    label: "Cooperative Savings",
    aliases: ["cooperative savings","savings group","tontine","cooperative-savings"],
    keywords: ["finance","cooperative","savings","cooperative savings","savings group","tontine","cooperative-savings"],
  },
  {
    key: "cosmetics",
    path: "/transaction-icons/shopping/cosmetics.svg",
    category: "SHOPPING",
    label: "Cosmetics",
    aliases: ["cosmetics"],
    keywords: ["shopping","cosmetics"],
  },
  {
    key: "course",
    path: "/transaction-icons/education/course.svg",
    category: "EDUCATION",
    label: "Course",
    aliases: ["course"],
    keywords: ["education","course"],
  },
  {
    key: "credit-card",
    path: "/transaction-icons/finance/credit-card.svg",
    category: "FINANCE",
    label: "Credit Card",
    aliases: ["credit-card","credit card"],
    keywords: ["finance","credit","card","credit-card","credit card"],
  },
  {
    key: "crypto",
    path: "/transaction-icons/finance/crypto.svg",
    category: "FINANCE",
    label: "Crypto",
    aliases: ["crypto"],
    keywords: ["finance","crypto"],
  },
  {
    key: "customs",
    path: "/transaction-icons/delivery/customs.svg",
    category: "DELIVERY",
    label: "Customs",
    aliases: ["customs"],
    keywords: ["delivery","customs"],
  },
  {
    key: "data-bundle",
    path: "/transaction-icons/utilities/data-bundle.svg",
    category: "UTILITIES",
    label: "Data Bundle",
    aliases: ["data bundle","mobile data","data-bundle"],
    keywords: ["utilities","data","bundle","data bundle","mobile data","data-bundle"],
  },
  {
    key: "delivery",
    path: "/transaction-icons/delivery/delivery.svg",
    category: "DELIVERY",
    label: "Delivery",
    aliases: ["delivery"],
    keywords: ["delivery"],
  },
  {
    key: "dentist",
    path: "/transaction-icons/health/dentist.svg",
    category: "HEALTH",
    label: "Dentist",
    aliases: ["dentist"],
    keywords: ["health","dentist"],
  },
  {
    key: "dividend",
    path: "/transaction-icons/income/dividend.svg",
    category: "INCOME",
    label: "Dividend",
    aliases: ["dividend"],
    keywords: ["income","dividend"],
  },
  {
    key: "doctor",
    path: "/transaction-icons/health/doctor.svg",
    category: "HEALTH",
    label: "Doctor",
    aliases: ["doctor","clinic"],
    keywords: ["health","doctor","clinic"],
  },
  {
    key: "domain",
    path: "/transaction-icons/digital/domain.svg",
    category: "DIGITAL",
    label: "Domain",
    aliases: ["domain"],
    keywords: ["digital","domain"],
  },
  {
    key: "electricity",
    path: "/transaction-icons/home/electricity.svg",
    category: "HOME",
    label: "Electricity",
    aliases: ["electricity","power utility"],
    keywords: ["home","electricity","power utility"],
  },
  {
    key: "electricity-prepaid",
    path: "/transaction-icons/home/electricity-prepaid.svg",
    category: "HOME",
    label: "Electricity Prepaid",
    aliases: ["prepaid electricity","electricity token","electricity-prepaid","electricity prepaid"],
    keywords: ["home","electricity","prepaid","prepaid electricity","electricity token","electricity-prepaid","electricity prepaid"],
  },
  {
    key: "electronics",
    path: "/transaction-icons/electronics/electronics.svg",
    category: "ELECTRONICS",
    label: "Electronics",
    aliases: ["electronics"],
    keywords: ["electronics"],
  },
  {
    key: "emergency-care",
    path: "/transaction-icons/health/emergency-care.svg",
    category: "HEALTH",
    label: "Emergency Care",
    aliases: ["emergency-care","emergency care"],
    keywords: ["health","emergency","care","emergency-care","emergency care"],
  },
  {
    key: "family-support",
    path: "/transaction-icons/community/family-support.svg",
    category: "COMMUNITY",
    label: "Family Support",
    aliases: ["family support","family transfer","family-support"],
    keywords: ["community","family","support","family support","family transfer","family-support"],
  },
  {
    key: "farm-input",
    path: "/transaction-icons/agriculture/farm-input.svg",
    category: "AGRICULTURE",
    label: "Farm Input",
    aliases: ["farm input","farm supplies","farm-input"],
    keywords: ["agriculture","farm","input","farm input","farm supplies","farm-input"],
  },
  {
    key: "fast-food",
    path: "/transaction-icons/food/fast-food.svg",
    category: "FOOD",
    label: "Fast Food",
    aliases: ["fast food","takeaway","fast-food"],
    keywords: ["food","fast","fast food","takeaway","fast-food"],
  },
  {
    key: "ferry",
    path: "/transaction-icons/transport/ferry.svg",
    category: "TRANSPORT",
    label: "Ferry",
    aliases: ["ferry"],
    keywords: ["transport","ferry"],
  },
  {
    key: "fishing",
    path: "/transaction-icons/agriculture/fishing.svg",
    category: "AGRICULTURE",
    label: "Fishing",
    aliases: ["fishing"],
    keywords: ["agriculture","fishing"],
  },
  {
    key: "fitness",
    path: "/transaction-icons/health/fitness.svg",
    category: "HEALTH",
    label: "Fitness",
    aliases: ["fitness"],
    keywords: ["health","fitness"],
  },
  {
    key: "flight",
    path: "/transaction-icons/travel/flight.svg",
    category: "TRAVEL",
    label: "Flight",
    aliases: ["flight","airfare"],
    keywords: ["travel","flight","airfare"],
  },
  {
    key: "food-delivery",
    path: "/transaction-icons/food/food-delivery.svg",
    category: "FOOD",
    label: "Food Delivery",
    aliases: ["food delivery","delivery food","takeaway","food-delivery"],
    keywords: ["food","delivery","food delivery","delivery food","takeaway","food-delivery"],
  },
  {
    key: "freelance-income",
    path: "/transaction-icons/income/freelance-income.svg",
    category: "INCOME",
    label: "Freelance Income",
    aliases: ["freelance income","contract income","freelance-income"],
    keywords: ["income","freelance","freelance income","contract income","freelance-income"],
  },
  {
    key: "fuel",
    path: "/transaction-icons/transport/fuel.svg",
    category: "TRANSPORT",
    label: "Fuel",
    aliases: ["fuel","petrol","gas station"],
    keywords: ["transport","fuel","petrol","gas station"],
  },
  {
    key: "funeral",
    path: "/transaction-icons/community/funeral.svg",
    category: "COMMUNITY",
    label: "Funeral",
    aliases: ["funeral"],
    keywords: ["community","funeral"],
  },
  {
    key: "furniture",
    path: "/transaction-icons/home/furniture.svg",
    category: "HOME",
    label: "Furniture",
    aliases: ["furniture"],
    keywords: ["home","furniture"],
  },
  {
    key: "gaming",
    path: "/transaction-icons/digital/gaming.svg",
    category: "DIGITAL",
    label: "Gaming",
    aliases: ["gaming"],
    keywords: ["digital","gaming"],
  },
  {
    key: "gas",
    path: "/transaction-icons/home/gas.svg",
    category: "HOME",
    label: "Gas",
    aliases: ["gas"],
    keywords: ["home","gas"],
  },
  {
    key: "generic-expense",
    path: "/transaction-icons/generic/generic-expense.svg",
    category: "GENERIC",
    label: "Generic Expense",
    aliases: ["generic expense","expense","generic-expense"],
    keywords: ["generic","expense","generic expense","generic-expense"],
  },
  {
    key: "generic-income",
    path: "/transaction-icons/generic/generic-income.svg",
    category: "GENERIC",
    label: "Generic Income",
    aliases: ["generic income","income","generic-income"],
    keywords: ["generic","income","generic income","generic-income"],
  },
  {
    key: "generic-refund",
    path: "/transaction-icons/generic/generic-refund.svg",
    category: "GENERIC",
    label: "Generic Refund",
    aliases: ["generic refund","generic-refund"],
    keywords: ["generic","refund","generic refund","generic-refund"],
  },
  {
    key: "generic-transaction",
    path: "/transaction-icons/generic/generic-transaction.svg",
    category: "GENERIC",
    label: "Generic Transaction",
    aliases: ["generic transaction","transaction","generic-transaction"],
    keywords: ["generic","transaction","generic transaction","generic-transaction"],
  },
  {
    key: "generic-transfer",
    path: "/transaction-icons/generic/generic-transfer.svg",
    category: "GENERIC",
    label: "Generic Transfer",
    aliases: ["generic transfer","generic-transfer"],
    keywords: ["generic","transfer","generic transfer","generic-transfer"],
  },
  {
    key: "gift",
    path: "/transaction-icons/community/gift.svg",
    category: "COMMUNITY",
    label: "Gift",
    aliases: ["gift"],
    keywords: ["community","gift"],
  },
  {
    key: "gift-income",
    path: "/transaction-icons/income/gift-income.svg",
    category: "INCOME",
    label: "Gift Income",
    aliases: ["gift income","gift-income"],
    keywords: ["income","gift","gift income","gift-income"],
  },
  {
    key: "government-fee",
    path: "/transaction-icons/finance/government-fee.svg",
    category: "FINANCE",
    label: "Government Fee",
    aliases: ["government fee","public fee","government-fee"],
    keywords: ["finance","government","fee","government fee","public fee","government-fee"],
  },
  {
    key: "grocery-store",
    path: "/transaction-icons/food/grocery-store.svg",
    category: "FOOD",
    label: "Grocery Store",
    aliases: ["grocery store","grocery","groceries","grocery-store"],
    keywords: ["food","grocery","store","grocery store","groceries","grocery-store"],
  },
  {
    key: "haircut",
    path: "/transaction-icons/shopping/haircut.svg",
    category: "SHOPPING",
    label: "Haircut",
    aliases: ["haircut"],
    keywords: ["shopping","haircut"],
  },
  {
    key: "health-insurance",
    path: "/transaction-icons/health/health-insurance.svg",
    category: "HEALTH",
    label: "Health Insurance",
    aliases: ["health insurance","medical insurance","health-insurance"],
    keywords: ["health","insurance","health insurance","medical insurance","health-insurance"],
  },
  {
    key: "health-supplements",
    path: "/transaction-icons/health/health-supplements.svg",
    category: "HEALTH",
    label: "Health Supplements",
    aliases: ["health-supplements","health supplements"],
    keywords: ["health","supplements","health-supplements","health supplements"],
  },
  {
    key: "home-improvement",
    path: "/transaction-icons/home/home-improvement.svg",
    category: "HOME",
    label: "Home Improvement",
    aliases: ["home-improvement","home improvement"],
    keywords: ["home","improvement","home-improvement","home improvement"],
  },
  {
    key: "home-maintenance",
    path: "/transaction-icons/home/home-maintenance.svg",
    category: "HOME",
    label: "Home Maintenance",
    aliases: ["home-maintenance","home maintenance"],
    keywords: ["home","maintenance","home-maintenance","home maintenance"],
  },
  {
    key: "home-security",
    path: "/transaction-icons/home/home-security.svg",
    category: "HOME",
    label: "Home Security",
    aliases: ["home-security","home security"],
    keywords: ["home","security","home-security","home security"],
  },
  {
    key: "hospital",
    path: "/transaction-icons/health/hospital.svg",
    category: "HEALTH",
    label: "Hospital",
    aliases: ["hospital"],
    keywords: ["health","hospital"],
  },
  {
    key: "hosting",
    path: "/transaction-icons/digital/hosting.svg",
    category: "DIGITAL",
    label: "Hosting",
    aliases: ["hosting"],
    keywords: ["digital","hosting"],
  },
  {
    key: "hotel",
    path: "/transaction-icons/travel/hotel.svg",
    category: "TRAVEL",
    label: "Hotel",
    aliases: ["hotel","lodging"],
    keywords: ["travel","hotel","lodging"],
  },
  {
    key: "household-goods",
    path: "/transaction-icons/shopping/household-goods.svg",
    category: "SHOPPING",
    label: "Household Goods",
    aliases: ["household-goods","household goods"],
    keywords: ["shopping","household","goods","household-goods","household goods"],
  },
  {
    key: "import-duty",
    path: "/transaction-icons/delivery/import-duty.svg",
    category: "DELIVERY",
    label: "Import Duty",
    aliases: ["import duty","customs duty","import-duty"],
    keywords: ["delivery","import","duty","import duty","customs duty","import-duty"],
  },
  {
    key: "insurance",
    path: "/transaction-icons/finance/insurance.svg",
    category: "FINANCE",
    label: "Insurance",
    aliases: ["insurance"],
    keywords: ["finance","insurance"],
  },
  {
    key: "interest",
    path: "/transaction-icons/finance/interest.svg",
    category: "FINANCE",
    label: "Interest",
    aliases: ["interest"],
    keywords: ["finance","interest"],
  },
  {
    key: "internet",
    path: "/transaction-icons/home/internet.svg",
    category: "HOME",
    label: "Internet",
    aliases: ["internet","broadband"],
    keywords: ["home","internet","broadband"],
  },
  {
    key: "investment-contribution",
    path: "/transaction-icons/finance/investment-contribution.svg",
    category: "FINANCE",
    label: "Investment Contribution",
    aliases: ["investment-contribution","investment contribution"],
    keywords: ["finance","investment","contribution","investment-contribution","investment contribution"],
  },
  {
    key: "investment-income",
    path: "/transaction-icons/income/investment-income.svg",
    category: "INCOME",
    label: "Investment Income",
    aliases: ["investment-income","investment income"],
    keywords: ["income","investment","investment-income","investment income"],
  },
  {
    key: "jewelry",
    path: "/transaction-icons/shopping/jewelry.svg",
    category: "SHOPPING",
    label: "Jewelry",
    aliases: ["jewelry"],
    keywords: ["shopping","jewelry"],
  },
  {
    key: "laboratory",
    path: "/transaction-icons/health/laboratory.svg",
    category: "HEALTH",
    label: "Laboratory",
    aliases: ["laboratory"],
    keywords: ["health","laboratory"],
  },
  {
    key: "legal",
    path: "/transaction-icons/professional/legal.svg",
    category: "PROFESSIONAL",
    label: "Legal",
    aliases: ["legal"],
    keywords: ["professional","legal"],
  },
  {
    key: "livestock",
    path: "/transaction-icons/agriculture/livestock.svg",
    category: "AGRICULTURE",
    label: "Livestock",
    aliases: ["livestock"],
    keywords: ["agriculture","livestock"],
  },
  {
    key: "loan",
    path: "/transaction-icons/finance/loan.svg",
    category: "FINANCE",
    label: "Loan",
    aliases: ["loan"],
    keywords: ["finance","loan"],
  },
  {
    key: "loan-payment",
    path: "/transaction-icons/finance/loan-payment.svg",
    category: "FINANCE",
    label: "Loan Payment",
    aliases: ["loan-payment","loan payment"],
    keywords: ["finance","loan","payment","loan-payment","loan payment"],
  },
  {
    key: "logistics",
    path: "/transaction-icons/transport/logistics.svg",
    category: "TRANSPORT",
    label: "Logistics",
    aliases: ["logistics"],
    keywords: ["transport","logistics"],
  },
  {
    key: "luggage",
    path: "/transaction-icons/travel/luggage.svg",
    category: "TRAVEL",
    label: "Luggage",
    aliases: ["luggage"],
    keywords: ["travel","luggage"],
  },
  {
    key: "market",
    path: "/transaction-icons/food/market.svg",
    category: "FOOD",
    label: "Market",
    aliases: ["market","local market","informal market"],
    keywords: ["food","market","local market","informal market"],
  },
  {
    key: "mental-wellness",
    path: "/transaction-icons/health/mental-wellness.svg",
    category: "HEALTH",
    label: "Mental Wellness",
    aliases: ["mental-wellness","mental wellness"],
    keywords: ["health","mental","wellness","mental-wellness","mental wellness"],
  },
  {
    key: "metro",
    path: "/transaction-icons/transport/metro.svg",
    category: "TRANSPORT",
    label: "Metro",
    aliases: ["metro"],
    keywords: ["transport","metro"],
  },
  {
    key: "microfinance",
    path: "/transaction-icons/finance/microfinance.svg",
    category: "FINANCE",
    label: "Microfinance",
    aliases: ["microfinance","micro finance"],
    keywords: ["finance","microfinance","micro finance"],
  },
  {
    key: "mobile-money",
    path: "/transaction-icons/finance/mobile-money.svg",
    category: "FINANCE",
    label: "Mobile Money",
    aliases: ["mobile money","momo","m-pesa","mpesa","orange money","mobile-money"],
    keywords: ["finance","mobile","money","mobile money","momo","m-pesa","mpesa","orange money","mobile-money"],
  },
  {
    key: "mobile-phone",
    path: "/transaction-icons/home/mobile-phone.svg",
    category: "HOME",
    label: "Mobile Phone",
    aliases: ["mobile phone","phone bill","mobile-phone"],
    keywords: ["home","mobile","phone","mobile phone","phone bill","mobile-phone"],
  },
  {
    key: "mortgage",
    path: "/transaction-icons/home/mortgage.svg",
    category: "HOME",
    label: "Mortgage",
    aliases: ["mortgage"],
    keywords: ["home","mortgage"],
  },
  {
    key: "motorbike",
    path: "/transaction-icons/transport/motorbike.svg",
    category: "TRANSPORT",
    label: "Motorbike",
    aliases: ["motorbike","motorcycle taxi","boda boda","okada"],
    keywords: ["transport","motorbike","motorcycle taxi","boda boda","okada"],
  },
  {
    key: "music",
    path: "/transaction-icons/digital/music.svg",
    category: "DIGITAL",
    label: "Music",
    aliases: ["music","audio"],
    keywords: ["digital","music","audio"],
  },
  {
    key: "news",
    path: "/transaction-icons/digital/news.svg",
    category: "DIGITAL",
    label: "News",
    aliases: ["news"],
    keywords: ["digital","news"],
  },
  {
    key: "office-supplies",
    path: "/transaction-icons/electronics/office-supplies.svg",
    category: "ELECTRONICS",
    label: "Office Supplies",
    aliases: ["office-supplies","office supplies"],
    keywords: ["electronics","office","supplies","office-supplies","office supplies"],
  },
  {
    key: "online-learning",
    path: "/transaction-icons/education/online-learning.svg",
    category: "EDUCATION",
    label: "Online Learning",
    aliases: ["online-learning","online learning"],
    keywords: ["education","online","learning","online-learning","online learning"],
  },
  {
    key: "online-shopping",
    path: "/transaction-icons/shopping/online-shopping.svg",
    category: "SHOPPING",
    label: "Online Shopping",
    aliases: ["online-shopping","online shopping"],
    keywords: ["shopping","online","online-shopping","online shopping"],
  },
  {
    key: "optician",
    path: "/transaction-icons/health/optician.svg",
    category: "HEALTH",
    label: "Optician",
    aliases: ["optician"],
    keywords: ["health","optician"],
  },
  {
    key: "parking",
    path: "/transaction-icons/transport/parking.svg",
    category: "TRANSPORT",
    label: "Parking",
    aliases: ["parking"],
    keywords: ["transport","parking"],
  },
  {
    key: "passport",
    path: "/transaction-icons/travel/passport.svg",
    category: "TRAVEL",
    label: "Passport",
    aliases: ["passport"],
    keywords: ["travel","passport"],
  },
  {
    key: "pet-food",
    path: "/transaction-icons/pets/pet-food.svg",
    category: "PETS",
    label: "Pet Food",
    aliases: ["pet-food","pet food"],
    keywords: ["pets","pet","food","pet-food","pet food"],
  },
  {
    key: "pets",
    path: "/transaction-icons/pets/pets.svg",
    category: "PETS",
    label: "Pets",
    aliases: ["pets"],
    keywords: ["pets"],
  },
  {
    key: "pharmacy",
    path: "/transaction-icons/health/pharmacy.svg",
    category: "HEALTH",
    label: "Pharmacy",
    aliases: ["pharmacy","chemist"],
    keywords: ["health","pharmacy","chemist"],
  },
  {
    key: "phone",
    path: "/transaction-icons/electronics/phone.svg",
    category: "ELECTRONICS",
    label: "Phone",
    aliases: ["phone"],
    keywords: ["electronics","phone"],
  },
  {
    key: "postal-service",
    path: "/transaction-icons/delivery/postal-service.svg",
    category: "DELIVERY",
    label: "Postal Service",
    aliases: ["postal-service","postal service"],
    keywords: ["delivery","postal","service","postal-service","postal service"],
  },
  {
    key: "produce",
    path: "/transaction-icons/food/produce.svg",
    category: "FOOD",
    label: "Produce",
    aliases: ["produce"],
    keywords: ["food","produce"],
  },
  {
    key: "property-tax",
    path: "/transaction-icons/home/property-tax.svg",
    category: "HOME",
    label: "Property Tax",
    aliases: ["property-tax","property tax"],
    keywords: ["home","property","tax","property-tax","property tax"],
  },
  {
    key: "public-transport",
    path: "/transaction-icons/transport/public-transport.svg",
    category: "TRANSPORT",
    label: "Public Transport",
    aliases: ["public transport","transit","public-transport"],
    keywords: ["transport","public","public transport","transit","public-transport"],
  },
  {
    key: "refund",
    path: "/transaction-icons/income/refund.svg",
    category: "INCOME",
    label: "Refund",
    aliases: ["refund","reversal"],
    keywords: ["income","refund","reversal"],
  },
  {
    key: "religious-giving",
    path: "/transaction-icons/community/religious-giving.svg",
    category: "COMMUNITY",
    label: "Religious Giving",
    aliases: ["religious-giving","religious giving"],
    keywords: ["community","religious","giving","religious-giving","religious giving"],
  },
  {
    key: "remittance",
    path: "/transaction-icons/finance/remittance.svg",
    category: "FINANCE",
    label: "Remittance",
    aliases: ["remittance","money transfer"],
    keywords: ["finance","remittance","money transfer"],
  },
  {
    key: "rent",
    path: "/transaction-icons/home/rent.svg",
    category: "HOME",
    label: "Rent",
    aliases: ["rent","rental"],
    keywords: ["home","rent","rental"],
  },
  {
    key: "restaurant",
    path: "/transaction-icons/food/restaurant.svg",
    category: "FOOD",
    label: "Restaurant",
    aliases: ["restaurant","dining","diner"],
    keywords: ["food","restaurant","dining","diner"],
  },
  {
    key: "ride-hailing",
    path: "/transaction-icons/transport/ride-hailing.svg",
    category: "TRANSPORT",
    label: "Ride Hailing",
    aliases: ["ride hailing","ride-hailing"],
    keywords: ["transport","ride","hailing","ride hailing","ride-hailing"],
  },
  {
    key: "salary",
    path: "/transaction-icons/income/salary.svg",
    category: "INCOME",
    label: "Salary",
    aliases: ["salary","payroll","wages"],
    keywords: ["income","salary","payroll","wages"],
  },
  {
    key: "savings-deposit",
    path: "/transaction-icons/finance/savings-deposit.svg",
    category: "FINANCE",
    label: "Savings Deposit",
    aliases: ["savings-deposit","savings deposit"],
    keywords: ["finance","savings","deposit","savings-deposit","savings deposit"],
  },
  {
    key: "school",
    path: "/transaction-icons/education/school.svg",
    category: "EDUCATION",
    label: "School",
    aliases: ["school","education"],
    keywords: ["education","school"],
  },
  {
    key: "school-fees",
    path: "/transaction-icons/education/school-fees.svg",
    category: "EDUCATION",
    label: "School Fees",
    aliases: ["school fees","tuition","school-fees"],
    keywords: ["education","school","fees","school fees","tuition","school-fees"],
  },
  {
    key: "security",
    path: "/transaction-icons/professional/security.svg",
    category: "PROFESSIONAL",
    label: "Security",
    aliases: ["security"],
    keywords: ["professional","security"],
  },
  {
    key: "seed-and-crop",
    path: "/transaction-icons/agriculture/seed-and-crop.svg",
    category: "AGRICULTURE",
    label: "Seed And Crop",
    aliases: ["seed-and-crop","seed and crop"],
    keywords: ["agriculture","seed","and","crop","seed-and-crop","seed and crop"],
  },
  {
    key: "shipping",
    path: "/transaction-icons/delivery/shipping.svg",
    category: "DELIVERY",
    label: "Shipping",
    aliases: ["shipping"],
    keywords: ["delivery","shipping"],
  },
  {
    key: "shoes",
    path: "/transaction-icons/shopping/shoes.svg",
    category: "SHOPPING",
    label: "Shoes",
    aliases: ["shoes"],
    keywords: ["shopping","shoes"],
  },
  {
    key: "software",
    path: "/transaction-icons/digital/software.svg",
    category: "DIGITAL",
    label: "Software",
    aliases: ["software"],
    keywords: ["digital","software"],
  },
  {
    key: "sports-equipment",
    path: "/transaction-icons/shopping/sports-equipment.svg",
    category: "SHOPPING",
    label: "Sports Equipment",
    aliases: ["sports-equipment","sports equipment"],
    keywords: ["shopping","sports","equipment","sports-equipment","sports equipment"],
  },
  {
    key: "streaming",
    path: "/transaction-icons/digital/streaming.svg",
    category: "DIGITAL",
    label: "Streaming",
    aliases: ["streaming","video streaming"],
    keywords: ["digital","streaming","video streaming"],
  },
  {
    key: "student-loan",
    path: "/transaction-icons/education/student-loan.svg",
    category: "EDUCATION",
    label: "Student Loan",
    aliases: ["student-loan","student loan"],
    keywords: ["education","student","loan","student-loan","student loan"],
  },
  {
    key: "subscription",
    path: "/transaction-icons/digital/subscription.svg",
    category: "DIGITAL",
    label: "Subscription",
    aliases: ["subscription","recurring"],
    keywords: ["digital","subscription","recurring"],
  },
  {
    key: "supermarket",
    path: "/transaction-icons/food/supermarket.svg",
    category: "FOOD",
    label: "Supermarket",
    aliases: ["supermarket","grocery","groceries","grocery store"],
    keywords: ["food","supermarket","grocery","groceries","grocery store"],
  },
  {
    key: "tax",
    path: "/transaction-icons/finance/tax.svg",
    category: "FINANCE",
    label: "Tax",
    aliases: ["tax"],
    keywords: ["finance","tax"],
  },
  {
    key: "taxi",
    path: "/transaction-icons/transport/taxi.svg",
    category: "TRANSPORT",
    label: "Taxi",
    aliases: ["taxi","cab"],
    keywords: ["transport","taxi","cab"],
  },
  {
    key: "television",
    path: "/transaction-icons/utilities/television.svg",
    category: "UTILITIES",
    label: "Television",
    aliases: ["television"],
    keywords: ["utilities","television"],
  },
  {
    key: "toll",
    path: "/transaction-icons/transport/toll.svg",
    category: "TRANSPORT",
    label: "Toll",
    aliases: ["toll"],
    keywords: ["transport","toll"],
  },
  {
    key: "tourism",
    path: "/transaction-icons/travel/tourism.svg",
    category: "TRAVEL",
    label: "Tourism",
    aliases: ["tourism"],
    keywords: ["travel","tourism"],
  },
  {
    key: "toys",
    path: "/transaction-icons/shopping/toys.svg",
    category: "SHOPPING",
    label: "Toys",
    aliases: ["toys"],
    keywords: ["shopping","toys"],
  },
  {
    key: "train",
    path: "/transaction-icons/transport/train.svg",
    category: "TRANSPORT",
    label: "Train",
    aliases: ["train"],
    keywords: ["transport","train"],
  },
  {
    key: "transfer",
    path: "/transaction-icons/finance/transfer.svg",
    category: "FINANCE",
    label: "Transfer",
    aliases: ["transfer","bank transfer"],
    keywords: ["finance","transfer","bank transfer"],
  },
  {
    key: "travel",
    path: "/transaction-icons/travel/travel.svg",
    category: "TRAVEL",
    label: "Travel",
    aliases: ["travel","trip"],
    keywords: ["travel","trip"],
  },
  {
    key: "tutoring",
    path: "/transaction-icons/education/tutoring.svg",
    category: "EDUCATION",
    label: "Tutoring",
    aliases: ["tutoring"],
    keywords: ["education","tutoring"],
  },
  {
    key: "university",
    path: "/transaction-icons/education/university.svg",
    category: "EDUCATION",
    label: "University",
    aliases: ["university"],
    keywords: ["education","university"],
  },
  {
    key: "vehicle-insurance",
    path: "/transaction-icons/transport/vehicle-insurance.svg",
    category: "TRANSPORT",
    label: "Vehicle Insurance",
    aliases: ["vehicle-insurance","vehicle insurance"],
    keywords: ["transport","vehicle","insurance","vehicle-insurance","vehicle insurance"],
  },
  {
    key: "vet",
    path: "/transaction-icons/pets/vet.svg",
    category: "PETS",
    label: "Vet",
    aliases: ["vet"],
    keywords: ["pets","vet"],
  },
  {
    key: "visa",
    path: "/transaction-icons/travel/visa.svg",
    category: "TRAVEL",
    label: "Visa",
    aliases: ["visa"],
    keywords: ["travel","visa"],
  },
  {
    key: "vision-care",
    path: "/transaction-icons/health/vision-care.svg",
    category: "HEALTH",
    label: "Vision Care",
    aliases: ["vision-care","vision care"],
    keywords: ["health","vision","care","vision-care","vision care"],
  },
  {
    key: "wallet",
    path: "/transaction-icons/finance/wallet.svg",
    category: "FINANCE",
    label: "Wallet",
    aliases: ["wallet"],
    keywords: ["finance","wallet"],
  },
  {
    key: "waste-collection",
    path: "/transaction-icons/utilities/waste-collection.svg",
    category: "UTILITIES",
    label: "Waste Collection",
    aliases: ["waste-collection","waste collection"],
    keywords: ["utilities","waste","collection","waste-collection","waste collection"],
  },
  {
    key: "water",
    path: "/transaction-icons/home/water.svg",
    category: "HOME",
    label: "Water",
    aliases: ["water","water utility"],
    keywords: ["home","water","water utility"],
  },
  {
    key: "wedding",
    path: "/transaction-icons/community/wedding.svg",
    category: "COMMUNITY",
    label: "Wedding",
    aliases: ["wedding"],
    keywords: ["community","wedding"],
  },
  {
    key: "seafood",
    path: "/transaction-icons/food/seafood.svg",
    category: "FOOD",
    label: "Seafood",
    aliases: ["seafood"],
    keywords: ["food","seafood"],
  },
  {
    key: "street-food",
    path: "/transaction-icons/food/street-food.svg",
    category: "FOOD",
    label: "Street Food",
    aliases: ["street food","street vendor","food stall","street-food"],
    keywords: ["food","street","street food","street vendor","food stall","street-food"],
  },
  {
    key: "food-court",
    path: "/transaction-icons/food/food-court.svg",
    category: "FOOD",
    label: "Food Court",
    aliases: ["food-court","food court"],
    keywords: ["food","court","food-court","food court"],
  },
  {
    key: "meal-kit",
    path: "/transaction-icons/food/meal-kit.svg",
    category: "FOOD",
    label: "Meal Kit",
    aliases: ["meal kit","meal plan","meal-kit"],
    keywords: ["food","meal","kit","meal kit","meal plan","meal-kit"],
  },
  {
    key: "catering",
    path: "/transaction-icons/food/catering.svg",
    category: "FOOD",
    label: "Catering",
    aliases: ["catering"],
    keywords: ["food","catering"],
  },
  {
    key: "airport-transfer",
    path: "/transaction-icons/transport/airport-transfer.svg",
    category: "TRANSPORT",
    label: "Airport Transfer",
    aliases: ["airport transfer","airport-transfer"],
    keywords: ["transport","airport","transfer","airport transfer","airport-transfer"],
  },
  {
    key: "parking-fee",
    path: "/transaction-icons/transport/parking-fee.svg",
    category: "TRANSPORT",
    label: "Parking Fee",
    aliases: ["parking fee","parking-fee"],
    keywords: ["transport","parking","fee","parking fee","parking-fee"],
  },
  {
    key: "vehicle-registration",
    path: "/transaction-icons/transport/vehicle-registration.svg",
    category: "TRANSPORT",
    label: "Vehicle Registration",
    aliases: ["vehicle registration","registration fee","vehicle-registration"],
    keywords: ["transport","vehicle","registration","vehicle registration","registration fee","vehicle-registration"],
  },
  {
    key: "roadside-assistance",
    path: "/transaction-icons/transport/roadside-assistance.svg",
    category: "TRANSPORT",
    label: "Roadside Assistance",
    aliases: ["roadside assistance","roadside-assistance"],
    keywords: ["transport","roadside","assistance","roadside assistance","roadside-assistance"],
  },
  {
    key: "scooter",
    path: "/transaction-icons/transport/scooter.svg",
    category: "TRANSPORT",
    label: "Scooter",
    aliases: ["scooter"],
    keywords: ["transport","scooter"],
  },
  {
    key: "plumbing",
    path: "/transaction-icons/home/plumbing.svg",
    category: "HOME",
    label: "Plumbing",
    aliases: ["plumbing"],
    keywords: ["home","plumbing"],
  },
  {
    key: "roofing",
    path: "/transaction-icons/home/roofing.svg",
    category: "HOME",
    label: "Roofing",
    aliases: ["roofing"],
    keywords: ["home","roofing"],
  },
  {
    key: "moving-service",
    path: "/transaction-icons/home/moving-service.svg",
    category: "HOME",
    label: "Moving Service",
    aliases: ["moving-service","moving service"],
    keywords: ["home","moving","service","moving-service","moving service"],
  },
  {
    key: "utilities-bundle",
    path: "/transaction-icons/home/utilities-bundle.svg",
    category: "HOME",
    label: "Utilities Bundle",
    aliases: ["utilities bundle","utility bill","utilities-bundle"],
    keywords: ["home","utilities","bundle","utilities bundle","utility bill","utilities-bundle"],
  },
  {
    key: "home-decor",
    path: "/transaction-icons/home/home-decor.svg",
    category: "HOME",
    label: "Home Decor",
    aliases: ["home-decor","home decor"],
    keywords: ["home","decor","home-decor","home decor"],
  },
  {
    key: "physiotherapy",
    path: "/transaction-icons/health/physiotherapy.svg",
    category: "HEALTH",
    label: "Physiotherapy",
    aliases: ["physiotherapy"],
    keywords: ["health","physiotherapy"],
  },
  {
    key: "maternal-care",
    path: "/transaction-icons/health/maternal-care.svg",
    category: "HEALTH",
    label: "Maternal Care",
    aliases: ["maternal care","maternity","maternal-care"],
    keywords: ["health","maternal","care","maternal care","maternity","maternal-care"],
  },
  {
    key: "dental-care",
    path: "/transaction-icons/health/dental-care.svg",
    category: "HEALTH",
    label: "Dental Care",
    aliases: ["dental-care","dental care"],
    keywords: ["health","dental","care","dental-care","dental care"],
  },
  {
    key: "medical-devices",
    path: "/transaction-icons/health/medical-devices.svg",
    category: "HEALTH",
    label: "Medical Devices",
    aliases: ["medical-devices","medical devices"],
    keywords: ["health","medical","devices","medical-devices","medical devices"],
  },
  {
    key: "clinic",
    path: "/transaction-icons/health/clinic.svg",
    category: "HEALTH",
    label: "Clinic",
    aliases: ["clinic"],
    keywords: ["health","clinic"],
  },
  {
    key: "exam-fee",
    path: "/transaction-icons/education/exam-fee.svg",
    category: "EDUCATION",
    label: "Exam Fee",
    aliases: ["exam fee","exam fees","exam-fee"],
    keywords: ["education","exam","fee","exam fee","exam fees","exam-fee"],
  },
  {
    key: "uniforms",
    path: "/transaction-icons/education/uniforms.svg",
    category: "EDUCATION",
    label: "Uniforms",
    aliases: ["uniforms"],
    keywords: ["education","uniforms"],
  },
  {
    key: "stationery",
    path: "/transaction-icons/education/stationery.svg",
    category: "EDUCATION",
    label: "Stationery",
    aliases: ["stationery"],
    keywords: ["education","stationery"],
  },
  {
    key: "language-course",
    path: "/transaction-icons/education/language-course.svg",
    category: "EDUCATION",
    label: "Language Course",
    aliases: ["language course","language learning","language-course"],
    keywords: ["education","language","course","language course","language learning","language-course"],
  },
  {
    key: "education-savings",
    path: "/transaction-icons/education/education-savings.svg",
    category: "EDUCATION",
    label: "Education Savings",
    aliases: ["education savings","education-savings"],
    keywords: ["education","savings","education savings","education-savings"],
  },
  {
    key: "department-store",
    path: "/transaction-icons/shopping/department-store.svg",
    category: "SHOPPING",
    label: "Department Store",
    aliases: ["department store","department-store"],
    keywords: ["shopping","department","store","department store","department-store"],
  },
  {
    key: "discount-store",
    path: "/transaction-icons/shopping/discount-store.svg",
    category: "SHOPPING",
    label: "Discount Store",
    aliases: ["discount store","discount-store"],
    keywords: ["shopping","discount","store","discount store","discount-store"],
  },
  {
    key: "florist",
    path: "/transaction-icons/shopping/florist.svg",
    category: "SHOPPING",
    label: "Florist",
    aliases: ["florist"],
    keywords: ["shopping","florist"],
  },
  {
    key: "craft-supplies",
    path: "/transaction-icons/shopping/craft-supplies.svg",
    category: "SHOPPING",
    label: "Craft Supplies",
    aliases: ["craft-supplies","craft supplies"],
    keywords: ["shopping","craft","supplies","craft-supplies","craft supplies"],
  },
  {
    key: "homewares",
    path: "/transaction-icons/shopping/homewares.svg",
    category: "SHOPPING",
    label: "Homewares",
    aliases: ["homewares"],
    keywords: ["shopping","homewares"],
  },
  {
    key: "app-store",
    path: "/transaction-icons/digital/app-store.svg",
    category: "DIGITAL",
    label: "App Store",
    aliases: ["app-store","app store"],
    keywords: ["digital","app","store","app-store","app store"],
  },
  {
    key: "mobile-app",
    path: "/transaction-icons/digital/mobile-app.svg",
    category: "DIGITAL",
    label: "Mobile App",
    aliases: ["mobile-app","mobile app"],
    keywords: ["digital","mobile","app","mobile-app","mobile app"],
  },
  {
    key: "cyber-security",
    path: "/transaction-icons/digital/cyber-security.svg",
    category: "DIGITAL",
    label: "Cyber Security",
    aliases: ["cyber-security","cyber security"],
    keywords: ["digital","cyber","security","cyber-security","cyber security"],
  },
  {
    key: "internet-cafe",
    path: "/transaction-icons/digital/internet-cafe.svg",
    category: "DIGITAL",
    label: "Internet Cafe",
    aliases: ["internet cafe","cyber cafe","internet-cafe"],
    keywords: ["digital","internet","cafe","internet cafe","cyber cafe","internet-cafe"],
  },
  {
    key: "digital-wallet",
    path: "/transaction-icons/digital/digital-wallet.svg",
    category: "DIGITAL",
    label: "Digital Wallet",
    aliases: ["digital wallet","e wallet","digital-wallet"],
    keywords: ["digital","wallet","digital wallet","e wallet","digital-wallet"],
  },
  {
    key: "forex",
    path: "/transaction-icons/finance/forex.svg",
    category: "FINANCE",
    label: "Forex",
    aliases: ["forex","foreign exchange"],
    keywords: ["finance","forex","foreign exchange"],
  },
  {
    key: "currency-exchange",
    path: "/transaction-icons/finance/currency-exchange.svg",
    category: "FINANCE",
    label: "Currency Exchange",
    aliases: ["currency exchange","exchange bureau","currency-exchange"],
    keywords: ["finance","currency","exchange","currency exchange","exchange bureau","currency-exchange"],
  },
  {
    key: "payment-processor",
    path: "/transaction-icons/finance/payment-processor.svg",
    category: "FINANCE",
    label: "Payment Processor",
    aliases: ["payment processor","payment processing","payment-processor"],
    keywords: ["finance","payment","processor","payment processor","payment processing","payment-processor"],
  },
  {
    key: "cash-on-delivery",
    path: "/transaction-icons/finance/cash-on-delivery.svg",
    category: "FINANCE",
    label: "Cash On Delivery",
    aliases: ["cash on delivery","cod","cash-on-delivery"],
    keywords: ["finance","cash","on","delivery","cash on delivery","cod","cash-on-delivery"],
  },
  {
    key: "merchant-services",
    path: "/transaction-icons/finance/merchant-services.svg",
    category: "FINANCE",
    label: "Merchant Services",
    aliases: ["merchant services","merchant-services"],
    keywords: ["finance","merchant","services","merchant services","merchant-services"],
  },
  {
    key: "transit-pass",
    path: "/transaction-icons/travel/transit-pass.svg",
    category: "TRAVEL",
    label: "Transit Pass",
    aliases: ["transit pass","transport pass","transit-pass"],
    keywords: ["travel","transit","pass","transit pass","transport pass","transit-pass"],
  },
  {
    key: "baggage-fee",
    path: "/transaction-icons/travel/baggage-fee.svg",
    category: "TRAVEL",
    label: "Baggage Fee",
    aliases: ["baggage fee","luggage fee","baggage-fee"],
    keywords: ["travel","baggage","fee","baggage fee","luggage fee","baggage-fee"],
  },
  {
    key: "travel-insurance",
    path: "/transaction-icons/travel/travel-insurance.svg",
    category: "TRAVEL",
    label: "Travel Insurance",
    aliases: ["travel insurance","travel-insurance"],
    keywords: ["travel","insurance","travel insurance","travel-insurance"],
  },
  {
    key: "hostel",
    path: "/transaction-icons/travel/hostel.svg",
    category: "TRAVEL",
    label: "Hostel",
    aliases: ["hostel"],
    keywords: ["travel","hostel"],
  },
  {
    key: "tour-guide",
    path: "/transaction-icons/travel/tour-guide.svg",
    category: "TRAVEL",
    label: "Tour Guide",
    aliases: ["tour guide","tour-guide"],
    keywords: ["travel","tour","guide","tour guide","tour-guide"],
  },
  {
    key: "cultural-event",
    path: "/transaction-icons/community/cultural-event.svg",
    category: "COMMUNITY",
    label: "Cultural Event",
    aliases: ["cultural event","cultural-event"],
    keywords: ["community","cultural","event","cultural event","cultural-event"],
  },
  {
    key: "elder-care",
    path: "/transaction-icons/community/elder-care.svg",
    category: "COMMUNITY",
    label: "Elder Care",
    aliases: ["elder care","elder-care"],
    keywords: ["community","elder","care","elder care","elder-care"],
  },
  {
    key: "mutual-aid",
    path: "/transaction-icons/community/mutual-aid.svg",
    category: "COMMUNITY",
    label: "Mutual Aid",
    aliases: ["mutual aid","mutual-aid"],
    keywords: ["community","mutual","aid","mutual aid","mutual-aid"],
  },
  {
    key: "birthday",
    path: "/transaction-icons/community/birthday.svg",
    category: "COMMUNITY",
    label: "Birthday",
    aliases: ["birthday"],
    keywords: ["community","birthday"],
  },
  {
    key: "celebration",
    path: "/transaction-icons/community/celebration.svg",
    category: "COMMUNITY",
    label: "Celebration",
    aliases: ["celebration"],
    keywords: ["community","celebration"],
  },
] as const satisfies readonly TransactionIconDefinition[];

export const TRANSACTION_ICON_BY_KEY: Readonly<Record<TransactionIconKey, TransactionIconDefinition>> =
  Object.freeze(
    Object.fromEntries(
      TRANSACTION_ICON_CATALOG.map((definition) => [definition.key, definition]),
    ) as unknown as Record<TransactionIconKey, TransactionIconDefinition>,
  );

export function isTransactionIconKey(value: string | null | undefined): value is TransactionIconKey {
  return Boolean(value && Object.hasOwn(TRANSACTION_ICON_BY_KEY, value));
}

export function getTransactionIconDefinition(key: TransactionIconKey): TransactionIconDefinition {
  return TRANSACTION_ICON_BY_KEY[key];
}

