import { FinancialReportDocument } from "@/modules/reports/ui/financial-report-document";
import type { FinancialReportDTO } from "@/modules/reports/domain/financial-report.types";

const report = {
  meta: {
    version: 1,
    language: "fr",
    locale: "fr-CM",
    timeZone: "Africa/Douala",
    generatedAt: "2026-11-02T10:00:00.000Z",
    generatedDate: "2026-11-02",
    fileName: "rapport-financier-octobre-2026.pdf",
    pages: [
      "cover",
      "executiveSummary",
      "incomeSpending",
      "categories",
      "transactions",
      "accounts",
      "recurring",
      "insights",
      "recommendations",
    ],
  },
  workspace: { name: "Pace", slug: "pace" },
  period: {
    key: "2026-10",
    firstDate: "2026-10-01",
    lastDate: "2026-10-31",
    monthLastDate: "2026-10-31",
    isPartial: false,
    previous: {
      key: "2026-09",
      firstDate: "2026-09-01",
      lastDate: "2026-09-30",
      isPartial: false,
    },
  },
  currency: { code: "XAF", workspaceCurrency: "XAF", excludedCurrencies: [] },
  hasActivity: true,
  executiveSummary: {
    income: {
      minor: "1250000",
      previousMinor: "1157000",
      deltaMinor: "93000",
      direction: "up",
      sentiment: "positive",
      percentage: "8",
    },
    spending: {
      minor: "682500",
      previousMinor: "609400",
      deltaMinor: "73100",
      direction: "up",
      sentiment: "negative",
      percentage: "12",
    },
    net: {
      minor: "567500",
      previousMinor: "547600",
      deltaMinor: "19900",
      direction: "up",
      sentiment: "positive",
      percentage: "5",
    },
    transactions: {
      current: 248,
      previous: 234,
      direction: "up",
      percentage: "6",
    },
    highlights: [
      {
        kind: "spendingChange",
        direction: "up",
        percentage: "12",
        categoryName: "Restaurant",
      },
      { kind: "netPositive", amountMinor: "567500" },
      { kind: "recurringShare", shareBps: 3800 },
    ],
  },
  incomeSpending: {
    months: [
      ["2026-05", "1050000", "720000", "330000"],
      ["2026-06", "950000", "690000", "260000"],
      ["2026-07", "1200000", "910000", "290000"],
      ["2026-08", "1180000", "900000", "280000"],
      ["2026-09", "1360000", "980000", "380000"],
      ["2026-10", "1250000", "682500", "567500"],
    ].map(([month, incomeMinor, spendingMinor, netMinor]) => ({
      month,
      incomeMinor,
      spendingMinor,
      netMinor,
      isPartial: false,
      isReportMonth: month === "2026-10",
    })),
  },
  categoryBreakdown: {
    totalMinor: "682500",
    items: [
      ["restaurant", "Restaurant", "180000", 2600],
      ["transport", "Transport", "120000", 1800],
      ["alimentation", "Alimentation", "95000", 1400],
      ["logement", "Logement", "80000", 1200],
      ["divertissement", "Divertissement", "60000", 900],
      ["sante", "Santé", "42500", 600],
      ["shopping", "Shopping", "38000", 600],
    ].map(([id, name, amountMinor, shareBps]) => ({
      id: String(id),
      name: String(name),
      amountMinor: String(amountMinor),
      previousMinor: "100000",
      shareBps: Number(shareBps),
      changePercentage: "12",
      direction: "up" as const,
      isUncategorized: false,
      categoryKey: String(id),
    })),
    other: null,
    evolution: [
      ["restaurant", "Restaurant", "180000", "36"],
      ["transport", "Transport", "120000", "26"],
      ["shopping", "Shopping", "38000", "32"],
      ["sante", "Santé", "42500", "-22"],
      ["logement", "Logement", "80000", "-11"],
    ].map(([id, name, amountMinor, changePercentage]) => ({
      id: String(id),
      name: String(name),
      amountMinor: String(amountMinor),
      previousMinor: "100000",
      shareBps: 1000,
      changePercentage: String(changePercentage),
      direction: "up" as const,
      isUncategorized: false,
      categoryKey: String(id),
    })),
  },
  keyTransactions: {
    totalCount: 8,
    items: [
      ["01", "Salaire", "ABC Group", "Revenus", "250000"],
      ["04", "Restaurant", "Le Nautique", "Restaurant", "-12000"],
      ["07", "Canal+", "Canal+", "Divertissement", "-12000"],
      ["10", "Internet", "MTN", "Télécom", "-25000"],
      ["14", "Carrefour Akwa", "Carrefour Akwa", "Alimentation", "-8500"],
      ["18", "Essence", "Total", "Transport", "-20000"],
      ["22", "Shopping", "Zara", "Shopping", "-35000"],
      ["28", "Netflix", "Netflix", "Divertissement", "-8500"],
    ].map(([day, title, merchantName, categoryName, signedMinor], index) => ({
      id: String(index),
      date: `2026-10-${day}`,
      kind: signedMinor.startsWith("-")
        ? ("EXPENSE" as const)
        : ("INCOME" as const),
      title,
      merchantName,
      categoryName,
      categoryKey: categoryName.toLowerCase(),
      accountName: "Compte principal",
      counterpartyAccountName: null,
      amountMinor: signedMinor.replace("-", ""),
      signedMinor,
    })),
  },
  accounts: {
    otherCurrencyCount: 0,
    items: [
      ["principal", "Compte principal", "450000", "900000", "682500", "217500"],
      ["epargne", "Épargne", "1200000", "350000", "50000", "300000"],
      ["liquidites", "Liquidités", "85000", "0", "25000", "-25000"],
    ].map(
      ([id, name, closingMinor, inflowsMinor, outflowsMinor, netMinor]) => ({
        id,
        name,
        type: "CHECKING" as const,
        typeLabel: id === "liquidites" ? "Espèces" : "•••• 4582",
        openingMinor: "0",
        closingMinor,
        balanceChangePercentage: "5",
        balanceDirection: "up" as const,
        inflowsMinor,
        outflowsMinor,
        netMinor,
        transactionCount: 1,
        isArchived: false,
      }),
    ),
  },
  recurring: {
    actualMinor: "260000",
    totalSpendingMinor: "682500",
    shareBps: 3800,
    paidCount: 7,
    projection: {
      firstDate: "2026-11-01",
      lastDate: "2026-11-30",
      outflowMinor: "260000",
      occurrenceCount: 7,
      hasVariableAmounts: false,
    },
    items: [
      ["Canal+", "Divertissement", "12000"],
      ["Netflix", "Divertissement", "8500"],
      ["Internet (MTN)", "Télécom", "25000"],
      ["Assurance", "Santé", "30000"],
      ["Salle de sport", "Santé", "20000"],
      ["Spotify", "Divertissement", "3500"],
      ["Cloud Storage", "Autres", "5000"],
    ].map(([name, categoryName, actualMinor], index) => ({
      id: String(index),
      name,
      categoryName,
      actualMinor,
      typicalAmountMinor: actualMinor,
      cadence: "monthly" as const,
      cadenceDays: 30,
      paymentCount: 1,
    })),
  },
  insights: {
    items: [
      {
        kind: "spendingUp",
      tone: "attention",
        percentage: "12",
        deltaMinor: "73100",
        categoryName: "Restaurant",
        categoryDeltaMinor: "65000",
      },
      {
        kind: "netImproved",
        tone: "positive",
        netMinor: "567500",
        deltaMinor: "19900",
      },
      {
        kind: "recurringHigh",
        tone: "neutral",
        shareBps: 3800,
        amountMinor: "260000",
      },
    ],
  },
  recommendations: {
    items: [
      {
        kind: "budgetCategory",
        categoryName: "Restaurant",
        percentage: "36",
        deltaMinor: "65000",
      },
      {
        kind: "reviewRecurring",
        count: 3,
        amountMinor: "28000",
        shareBps: 3800,
      },
      { kind: "keepSaving", savingsRateBps: 2000, netMinor: "567500" },
    ],
  },
} satisfies FinancialReportDTO;

export default function ReportPreviewPage() {
  return <FinancialReportDocument report={report} />;
}
