export type PlansUiLabels = {
  readonly createBudget: Readonly<Record<string, string>>;
  readonly createSavingsGoal: Readonly<Record<string, string>>;
  readonly budgetManagement: Readonly<Record<string, string>>;
  readonly title: string;
  readonly subtitle: string;
  readonly budgets: string;
  readonly all: string;
  readonly goals: string;
  readonly forecasts: string;
  readonly rules: string;
  readonly askPace: string;
  readonly newPlan: string;
  readonly monthlyBudgets: string;
  readonly monthlyBudgetsSubtitle: string;
  readonly budgeted: string;
  readonly spent: string;
  readonly remaining: string;
  readonly used: string;
  readonly overall: string;
  readonly status: string;
  readonly onTrack: string;
  readonly attention: string;
  readonly overBudget: string;
  readonly inactive: string;
  readonly savings: string;
  readonly savingsSubtitle: string;
  readonly seeAll: string;
  readonly target: string;
  readonly saved: string;
  readonly left: string;
  readonly targetDate: string;
  readonly budgetEmpty: string;
  readonly savingsEmpty: string;
  readonly planInsights: string;
  readonly insightOverBudget: string;
  readonly insightAttention: string;
  readonly insightOnTrack: string;
  readonly unavailable: string;
  readonly loading: string;
  readonly progress: string;
  readonly timeline: string;
  readonly transactions: string;
  readonly insights: string;
  readonly details: string;
  readonly emptyTransactions: string;
  readonly more: string;
  readonly actualSpending: string;
  readonly period: string;
  readonly category: string;
  readonly goalDetail: Readonly<Record<string, string>>;
};

const createBudgetLabels = {
  close: "Close",
  title: "New budget",
  subtitle: "Set a spending limit for a category and track your progress.",
  basicInfo: "Basic info",
  budgetName: "Budget name",
  budgetNameValue: "Food & dining",
  budgetNameHint: "Choose a clear name for this budget.",
  iconAndColour: "Icon and colour",
  iconPicker: "Budget icon",
  iconFood: "Food",
  iconTransport: "Transport",
  iconShopping: "Shopping",
  iconHome: "Home",
  iconHealth: "Health",
  iconEntertainment: "Entertainment",
  iconSubscriptions: "Subscriptions",
  iconBills: "Bills",
  iconEducation: "Education",
  iconTravel: "Travel",
  iconOther: "Other",
  description: "Description",
  optional: "(optional)",
  descriptionValue: "Restaurants, groceries, cafés and get-togethers…",
  categoryScope: "Category & scope",
  mainCategory: "Main category",
  category: "Category",
  scope: "Scope",
  entireCategory: "Entire category",
  selectedSubcategories: "Selected subcategories",
  subcategories: "Subcategories",
  selectCategory: "Select category",
  selectSubcategories: "Select subcategories",
  subcategoriesHint: "Leave blank to include the entire category.",
  noSubcategoriesAvailable: "No subcategories available",
  loadingCategories: "Loading categories…",
  categoryLoadError: "Categories could not be loaded. Please try again.",
  removeSubcategory: "Remove subcategory",
  subcategoriesValue: "Restaurants · Groceries · Cafés",
  amountPeriod: "Amount & period",
  budgetAmount: "Budget amount",
  amountValue: "120,000",
  currency: "FCFA",
  period: "Period",
  monthly: "Monthly",
  weekly: "Weekly",
  custom: "Custom",
  periodValue: "September 2026",
  amountHint: "Maximum amount to spend for this period.",
  selectPeriod: "Select period",
  invalidAmount: "Enter an amount greater than zero.",
  invalidPeriod: "Select a valid period.",
  advancedOptions: "Advanced options",
  monthlyResetTitle: "Monthly reset",
  monthlyResetHint: "This budget starts fresh on the first day of each month.",
  preview: "Preview",
  previewDescription: "Restaurants, groceries, cafés…",
  previewCategoryFallback: "No category selected",
  previewAmountFallback: "No amount set",
  previewPeriodFallback: "No period selected",
  notStarted: "Not started",
  amount: "Amount",
  progressExample: "Progress example",
  notice:
    "This budget will begin on {startsOn} and reset automatically on {resetsOn}.",
  cancel: "Cancel",
  create: "Create budget",
  creating: "Creating…",
  invalidCategory: "Select a valid category.",
  invalidCurrency: "This currency is not available for this workspace.",
  createError: "We could not create this budget. Please try again.",
};

const createSavingsGoalLabels = {
  close: "Close",
  title: "New savings goal",
  subtitle: "Set a clear target and track only the progress you enter.",
  details: "Goal details",
  name: "Goal name",
  namePlaceholder: "e.g. Emergency fund",
  nameHint: "Give this goal a name you will recognize.",
  iconAndColour: "Icon and colour",
  iconPicker: "Goal icon",
  target: "Target",
  targetAmount: "Target amount",
  targetHint: "The full amount you want to save.",
  targetDate: "Target date",
  targetDateHint: "Optional. This does not schedule transfers.",
  initialProgress: "Initial progress",
  addInitialProgress: "Set an amount already saved",
  currentSaved: "Already saved",
  currentSavedHint: "This records explicit progress only.",
  preview: "Preview",
  previewName: "Savings goal",
  previewAmountFallback: "No target set",
  noTargetDate: "No target date",
  saved: "saved",
  remaining: "remaining",
  progress: "Progress",
  noMoneyNotice:
    "Creating this goal will not move money, change balances, or create transactions.",
  cancel: "Cancel",
  create: "Create goal",
  creating: "Creating…",
  invalidName: "Enter a goal name.",
  invalidAmount: "Enter an amount greater than zero.",
  invalidProgress: "Enter a valid saved amount.",
  invalidDate: "Enter a valid target date.",
  invalidCurrency: "This currency is not available for this workspace.",
  createError: "We could not create this savings goal. Please try again.",
};

const budgetManagementLabels = {
  edit: "Edit budget",
  archive: "Archive budget",
  editTitle: "Edit budget",
  editDescription: "Update the planning details for this budget.",
  overall: "Overall spending",
  archived: "Archived",
  save: "Save changes",
  saving: "Saving…",
  editError: "We could not save your changes. Please try again.",
  changed: "This budget changed since you opened it.",
  reload: "Reload latest",
  archiveTitle: "Archive budget",
  archiveDescription:
    "This budget will be removed from active plans, but its history will be preserved. No transactions or balances will be changed.",
  archiving: "Archiving…",
  archiveError: "We could not archive this budget. Please try again.",
};

const labels: Record<"en" | "fr" | "de", PlansUiLabels> = {
  en: {
    createBudget: createBudgetLabels,
    createSavingsGoal: createSavingsGoalLabels,
    budgetManagement: budgetManagementLabels,
    title: "Plans",
    subtitle: "Plan your budgets and savings goals with clarity.",
    budgets: "Budgets",
    all: "All",
    goals: "Goals",
    forecasts: "Forecasts",
    rules: "Rules",
    askPace: "Ask Pace",
    newPlan: "New plan",
    monthlyBudgets: "Monthly budgets",
    monthlyBudgetsSubtitle: "Track your category spending this month.",
    budgeted: "Budgeted",
    spent: "Spent",
    remaining: "Remaining",
    used: "% used",
    overall: "Overall spending",
    status: "Status",
    onTrack: "On track",
    attention: "Attention",
    overBudget: "Over budget",
    inactive: "Inactive",
    savings: "Savings goals",
    savingsSubtitle: "Move your projects forward faster.",
    seeAll: "See all",
    target: "Target",
    saved: "saved",
    left: "left",
    targetDate: "Target date",
    budgetEmpty: "No active budgets for this period.",
    savingsEmpty: "No savings goals yet.",
    planInsights: "Plan insights",
    insightOverBudget: "A budget needs attention",
    insightAttention: "A category is nearing its budget",
    insightOnTrack: "Your budgets are on track",
    unavailable: "This section is not available yet.",
    loading: "Updating plan…",
    progress: "Budget progress",
    timeline: "Spending over time",
    transactions: "Budget transactions",
    insights: "Budget insights",
    details: "Budget details",
    emptyTransactions: "No contributing transactions yet.",
    more: "More options",
    actualSpending: "Actual posted spending",
    period: "Period",
    category: "Category",
    goalDetail: {
      back: "Back to Plans",
      targetAmount: "Target amount",
      contributed: "Saved",
      progressPercent: "Progress",
      completed: "Completed",
      active: "Active",
      paused: "Paused",
      archived: "Archived",
      progress: "Goal progress",
      remaining: "remaining",
      history: "Progress over time",
      historyEmpty: "Progress history is not available yet.",
      contributions: "Contribution history",
      contributionsEmpty:
        "No canonical contribution history is available for this goal.",
      addContribution: "Add contribution",
      addingContribution: "Adding…",
      contributionHelper: "This updates your goal progress only. No money will be moved automatically.",
      amount: "Amount",
      effectiveDate: "Effective date",
      invalidEffectiveDate: "Enter a valid effective date.",
      noteOptional: "Note (optional)",
      contributionInvalid: "Enter an amount greater than zero and check the effective date.",
      contributionUnavailable: "This goal is no longer available for contributions.",
      contributionError: "We could not add this contribution. Please try again.",
      contribution: "Contribution",
      reversal: "Reversal",
      insights: "Goal insights",
      details: "Goal details",
      created: "Created",
      currency: "Currency",
      daysRemaining: "{days} days remaining",
      requiredDaily: "Required daily pace",
      targetDate: "Target date",
      noTargetDate: "No target date",
      completedDescription: "This goal has reached its target.",
      more: "More options",
      status: "Status",
      cancel: "Cancel",
      edit: "Edit goal",
      archive: "Archive goal",
      complete: "Complete goal",
      editTitle: "Edit savings goal",
      editDescription: "Update this goal’s planning details.",
      save: "Save changes",
      saving: "Saving…",
      editError: "We could not save your changes. Please try again.",
      archiveTitle: "Archive savings goal",
      archiveDescription: "This goal will leave active plans. Its progress and history will be preserved. No money is moved and no transaction is deleted.",
      archiving: "Archiving…",
      archiveError: "We could not archive this goal. Please try again.",
      completeTitle: "Complete savings goal",
      completeDescription: "This is a planning status only. It does not move money, create a transaction, transfer funds, or change account balances.",
      completing: "Completing…",
      completeError: "We could not complete this goal. Please try again.",
      changed: "This goal changed since you opened it.",
      reload: "Reload latest",
    },
  },
  fr: {
    createSavingsGoal: {
      close: "Fermer",
      title: "Nouvel objectif d’épargne",
      subtitle:
        "Définissez une cible claire et suivez uniquement les progrès que vous saisissez.",
      details: "Détails de l’objectif",
      name: "Nom de l’objectif",
      namePlaceholder: "ex. Fonds d’urgence",
      nameHint: "Donnez un nom facile à reconnaître.",
      iconAndColour: "Icône et couleur",
      iconPicker: "Icône de l’objectif",
      target: "Cible",
      targetAmount: "Montant cible",
      targetHint: "Le montant total à épargner.",
      targetDate: "Date cible",
      targetDateHint: "Facultatif. Aucun virement n’est programmé.",
      initialProgress: "Progression initiale",
      addInitialProgress: "Indiquer un montant déjà épargné",
      currentSaved: "Déjà épargné",
      currentSavedHint: "Enregistre uniquement une progression explicite.",
      preview: "Aperçu",
      previewName: "Objectif d’épargne",
      previewAmountFallback: "Aucune cible",
      noTargetDate: "Aucune date cible",
      saved: "épargnés",
      remaining: "restant",
      progress: "Progression",
      noMoneyNotice:
        "La création de cet objectif ne déplace pas d’argent, ne modifie aucun solde et ne crée aucune transaction.",
      cancel: "Annuler",
      create: "Créer l’objectif",
      creating: "Création…",
      invalidName: "Saisissez un nom d’objectif.",
      invalidAmount: "Saisissez un montant supérieur à zéro.",
      invalidProgress: "Saisissez un montant épargné valide.",
      invalidDate: "Saisissez une date cible valide.",
      invalidCurrency:
        "Cette devise n’est pas disponible pour cet espace de travail.",
      createError:
        "Impossible de créer cet objectif d’épargne. Veuillez réessayer.",
    },
    createBudget: {
      close: "Fermer",
      title: "Nouveau budget",
      subtitle: "Fixez une limite pour une catégorie et suivez vos progrès.",
      basicInfo: "Informations générales",
      budgetName: "Nom du budget",
      budgetNameValue: "Alimentation et sorties",
      budgetNameHint: "Choisissez un nom clair pour ce budget.",
      iconAndColour: "Icône et couleur",
      iconPicker: "Icône du budget",
      iconFood: "Alimentation",
      iconTransport: "Transport",
      iconShopping: "Achats",
      iconHome: "Logement",
      iconHealth: "Santé",
      iconEntertainment: "Divertissement",
      iconSubscriptions: "Abonnements",
      iconBills: "Factures",
      iconEducation: "Éducation",
      iconTravel: "Voyages",
      iconOther: "Autre",
      description: "Description",
      optional: "(facultatif)",
      descriptionValue: "Restaurants, courses, cafés et sorties…",
      categoryScope: "Catégorie et portée",
      mainCategory: "Catégorie principale",
      budgetAmount: "Montant du budget",
      period: "Période",
      amountHint: "Montant maximal à dépenser pour cette période.",
      selectPeriod: "Sélectionner une période",
      invalidAmount: "Saisissez un montant supérieur à zéro.",
      invalidPeriod: "Sélectionnez une période valide.",
      category: "Catégorie",
      scope: "Portée",
      entireCategory: "Toute la catégorie",
      selectedSubcategories: "Sous-catégories sélectionnées",
      subcategories: "Sous-catégories",
      selectCategory: "Sélectionner une catégorie",
      selectSubcategories: "Sélectionner des sous-catégories",
      subcategoriesHint: "Laissez vide pour inclure toute la catégorie.",
      noSubcategoriesAvailable: "Aucune sous-catégorie disponible",
      loadingCategories: "Chargement des catégories…",
      categoryLoadError:
        "Les catégories n’ont pas pu être chargées. Veuillez réessayer.",
      removeSubcategory: "Supprimer la sous-catégorie",
      advancedOptions: "Options avancées",
      monthlyResetTitle: "Réinitialisation mensuelle",
      monthlyResetHint:
        "Ce budget recommence à zéro le premier jour de chaque mois.",
      preview: "Aperçu",
      previewDescription: "Restaurants, courses, cafés…",
      previewCategoryFallback: "Aucune catégorie sélectionnée",
      previewAmountFallback: "Aucun montant défini",
      previewPeriodFallback: "Aucune période sélectionnée",
      notStarted: "Pas encore commencé",
      amount: "Montant",
      progressExample: "Exemple de progression",
      notice:
        "Ce budget commencera le {startsOn} et se réinitialisera automatiquement le {resetsOn}.",
      cancel: "Annuler",
      create: "Créer le budget",
      creating: "Création…",
      invalidCategory: "Sélectionnez une catégorie valide.",
      invalidCurrency:
        "Cette devise n’est pas disponible pour cet espace de travail.",
      createError: "Impossible de créer ce budget. Veuillez réessayer.",
    },
    budgetManagement: {
      edit: "Modifier le budget",
      archive: "Archiver le budget",
      editTitle: "Modifier le budget",
      editDescription:
        "Mettez à jour les informations de planification de ce budget.",
      overall: "Dépenses globales",
      archived: "Archivé",
      save: "Enregistrer les modifications",
      saving: "Enregistrement…",
      editError:
        "Impossible d’enregistrer vos modifications. Veuillez réessayer.",
      changed: "Ce budget a changé depuis son ouverture.",
      reload: "Recharger la dernière version",
      archiveTitle: "Archiver le budget",
      archiveDescription:
        "Ce budget sera retiré des plans actifs, mais son historique sera conservé. Aucune transaction ni aucun solde ne seront modifiés.",
      archiving: "Archivage…",
      archiveError: "Impossible d’archiver ce budget. Veuillez réessayer.",
    },
    title: "Plans",
    subtitle: "Planifiez vos budgets et objectifs d’épargne en toute clarté.",
    budgets: "Budgets",
    all: "Tout",
    goals: "Objectifs",
    forecasts: "Prévisions",
    rules: "Règles",
    askPace: "Demander à Pace",
    newPlan: "Nouveau plan",
    monthlyBudgets: "Budgets mensuels",
    monthlyBudgetsSubtitle:
      "Suivez vos dépenses par catégorie pour ce mois-ci.",
    budgeted: "Budgété",
    spent: "Dépensé",
    remaining: "Restant",
    used: "% utilisé",
    overall: "Dépenses globales",
    status: "Statut",
    onTrack: "Sur la bonne voie",
    attention: "Attention",
    overBudget: "Budget dépassé",
    inactive: "Inactif",
    savings: "Objectifs d’épargne",
    savingsSubtitle: "Avancez vers vos projets plus rapidement.",
    seeAll: "Tout voir",
    target: "Objectif",
    saved: "épargnés",
    left: "restant",
    targetDate: "Date cible",
    budgetEmpty: "Aucun budget actif pour cette période.",
    savingsEmpty: "Aucun objectif d’épargne pour le moment.",
    planInsights: "Aperçus du plan",
    insightOverBudget: "Un budget demande votre attention",
    insightAttention: "Une catégorie approche de son budget",
    insightOnTrack: "Vos budgets sont sur la bonne voie",
    unavailable: "Cette section n’est pas encore disponible.",
    loading: "Mise à jour du plan…",
    progress: "Progression du budget",
    timeline: "Dépenses dans le temps",
    transactions: "Transactions de ce budget",
    insights: "Aperçus du budget",
    details: "Détails du budget",
    emptyTransactions: "Aucune transaction contributrice pour le moment.",
    more: "Plus d’options",
    actualSpending: "Dépenses comptabilisées réelles",
    period: "Période",
    category: "Catégorie",
    goalDetail: {
      back: "Retour aux plans",
      targetAmount: "Montant cible",
      contributed: "Épargné",
      progressPercent: "Progression",
      completed: "Terminé",
      active: "Actif",
      paused: "En pause",
      archived: "Archivé",
      progress: "Progression de l’objectif",
      remaining: "restant",
      history: "Progression dans le temps",
      historyEmpty: "L’historique de progression n’est pas encore disponible.",
      contributions: "Historique des contributions",
      contributionsEmpty:
        "Aucun historique de contributions canonique n’est disponible pour cet objectif.",
      addContribution: "Ajouter une contribution",
      addingContribution: "Ajout…",
      contributionHelper: "Cela met à jour uniquement la progression de votre objectif. Aucun argent ne sera déplacé automatiquement.",
      amount: "Montant",
      effectiveDate: "Date d’effet",
      invalidEffectiveDate: "Saisissez une date d’effet valide.",
      noteOptional: "Note (facultatif)",
      contributionInvalid: "Saisissez un montant supérieur à zéro et vérifiez la date d’effet.",
      contributionUnavailable: "Cet objectif n’est plus disponible pour les contributions.",
      contributionError: "Nous n’avons pas pu ajouter cette contribution. Veuillez réessayer.",
      contribution: "Contribution",
      reversal: "Annulation",
      insights: "Aperçus de l’objectif",
      details: "Détails de l’objectif",
      created: "Créé",
      currency: "Devise",
      daysRemaining: "{days} jours restants",
      requiredDaily: "Rythme quotidien requis",
      targetDate: "Date cible",
      noTargetDate: "Aucune date cible",
      completedDescription: "Cet objectif a atteint son montant cible.",
      more: "Plus d’options",
      status: "Statut",
      cancel: "Annuler",
      edit: "Modifier l’objectif",
      archive: "Archiver l’objectif",
      complete: "Terminer l’objectif",
      editTitle: "Modifier l’objectif d’épargne",
      editDescription: "Mettez à jour les détails de planification de cet objectif.",
      save: "Enregistrer les modifications",
      saving: "Enregistrement…",
      editError: "Impossible d’enregistrer vos modifications. Veuillez réessayer.",
      archiveTitle: "Archiver l’objectif d’épargne",
      archiveDescription: "Cet objectif quittera les plans actifs. Sa progression et son historique seront conservés. Aucun argent ne sera déplacé et aucune transaction ne sera supprimée.",
      archiving: "Archivage…",
      archiveError: "Impossible d’archiver cet objectif. Veuillez réessayer.",
      completeTitle: "Terminer l’objectif d’épargne",
      completeDescription: "Il s’agit uniquement d’un état de planification. Cela ne déplace pas d’argent, ne crée pas de transaction, n’effectue pas de virement et ne modifie aucun solde.",
      completing: "Finalisation…",
      completeError: "Impossible de terminer cet objectif. Veuillez réessayer.",
      changed: "Cet objectif a changé depuis son ouverture.",
      reload: "Recharger la dernière version",
    },
  },
  de: {
    createSavingsGoal: {
      close: "Schließen",
      title: "Neues Sparziel",
      subtitle:
        "Lege ein klares Ziel fest und erfasse nur den Fortschritt, den du eingibst.",
      details: "Zieldetails",
      name: "Zielname",
      namePlaceholder: "z. B. Notgroschen",
      nameHint: "Gib dem Ziel einen eindeutigen Namen.",
      iconAndColour: "Symbol und Farbe",
      iconPicker: "Zielsymbol",
      target: "Ziel",
      targetAmount: "Zielbetrag",
      targetHint: "Der gesamte Betrag, den du sparen möchtest.",
      targetDate: "Zieldatum",
      targetDateHint: "Optional. Es werden keine Überweisungen geplant.",
      initialProgress: "Anfangsfortschritt",
      addInitialProgress: "Bereits gesparten Betrag festlegen",
      currentSaved: "Bereits gespart",
      currentSavedHint: "Erfasst nur expliziten Fortschritt.",
      preview: "Vorschau",
      previewName: "Sparziel",
      previewAmountFallback: "Kein Zielbetrag",
      noTargetDate: "Kein Zieldatum",
      saved: "gespart",
      remaining: "verbleibend",
      progress: "Fortschritt",
      noMoneyNotice:
        "Das Erstellen dieses Ziels bewegt kein Geld, ändert keine Salden und erstellt keine Transaktionen.",
      cancel: "Abbrechen",
      create: "Ziel erstellen",
      creating: "Wird erstellt…",
      invalidName: "Gib einen Zielnamen ein.",
      invalidAmount: "Gib einen Betrag größer als null ein.",
      invalidProgress: "Gib einen gültigen gesparten Betrag ein.",
      invalidDate: "Gib ein gültiges Zieldatum ein.",
      invalidCurrency:
        "Diese Währung ist für diesen Arbeitsbereich nicht verfügbar.",
      createError:
        "Dieses Sparziel konnte nicht erstellt werden. Bitte versuche es erneut.",
    },
    createBudget: {
      close: "Schließen",
      title: "Neues Budget",
      subtitle:
        "Legen Sie ein Ausgabenlimit für eine Kategorie fest und verfolgen Sie Ihren Fortschritt.",
      basicInfo: "Grundinformationen",
      budgetName: "Budgetname",
      budgetNameValue: "Essen und Ausgehen",
      budgetNameHint: "Wählen Sie einen eindeutigen Namen für dieses Budget.",
      iconAndColour: "Symbol und Farbe",
      iconPicker: "Budgetsymbol",
      iconFood: "Lebensmittel",
      iconTransport: "Transport",
      iconShopping: "Einkäufe",
      iconHome: "Wohnen",
      iconHealth: "Gesundheit",
      iconEntertainment: "Unterhaltung",
      iconSubscriptions: "Abonnements",
      iconBills: "Rechnungen",
      iconEducation: "Bildung",
      iconTravel: "Reisen",
      iconOther: "Sonstiges",
      description: "Beschreibung",
      optional: "(optional)",
      descriptionValue: "Restaurants, Lebensmittel, Cafés und Treffen…",
      categoryScope: "Kategorie und Umfang",
      mainCategory: "Hauptkategorie",
      budgetAmount: "Budgetbetrag",
      period: "Zeitraum",
      amountHint: "Maximaler Betrag für diesen Zeitraum.",
      selectPeriod: "Zeitraum auswählen",
      invalidAmount: "Geben Sie einen Betrag größer als null ein.",
      invalidPeriod: "Wählen Sie einen gültigen Zeitraum aus.",
      category: "Kategorie",
      scope: "Umfang",
      entireCategory: "Gesamte Kategorie",
      selectedSubcategories: "Ausgewählte Unterkategorien",
      subcategories: "Unterkategorien",
      selectCategory: "Kategorie auswählen",
      selectSubcategories: "Unterkategorien auswählen",
      subcategoriesHint:
        "Leer lassen, um die gesamte Kategorie einzuschließen.",
      noSubcategoriesAvailable: "Keine Unterkategorien verfügbar",
      loadingCategories: "Kategorien werden geladen…",
      categoryLoadError:
        "Kategorien konnten nicht geladen werden. Bitte versuchen Sie es erneut.",
      removeSubcategory: "Unterkategorie entfernen",
      advancedOptions: "Erweiterte Optionen",
      monthlyResetTitle: "Monatliche Zurücksetzung",
      monthlyResetHint: "Dieses Budget beginnt am ersten Tag jedes Monats neu.",
      preview: "Vorschau",
      previewDescription: "Restaurants, Lebensmittel, Cafés…",
      previewCategoryFallback: "Keine Kategorie ausgewählt",
      previewAmountFallback: "Kein Betrag festgelegt",
      previewPeriodFallback: "Kein Zeitraum ausgewählt",
      notStarted: "Noch nicht begonnen",
      amount: "Betrag",
      progressExample: "Fortschrittsbeispiel",
      notice:
        "Dieses Budget beginnt am {startsOn} und wird am {resetsOn} automatisch zurückgesetzt.",
      cancel: "Abbrechen",
      create: "Budget erstellen",
      creating: "Wird erstellt…",
      invalidCategory: "Wählen Sie eine gültige Kategorie aus.",
      invalidCurrency:
        "Diese Währung ist für diesen Arbeitsbereich nicht verfügbar.",
      createError:
        "Dieses Budget konnte nicht erstellt werden. Bitte versuchen Sie es erneut.",
    },
    budgetManagement: {
      edit: "Budget bearbeiten",
      archive: "Budget archivieren",
      editTitle: "Budget bearbeiten",
      editDescription: "Aktualisieren Sie die Planungsdetails dieses Budgets.",
      overall: "Gesamtausgaben",
      archived: "Archiviert",
      save: "Änderungen speichern",
      saving: "Wird gespeichert…",
      editError:
        "Ihre Änderungen konnten nicht gespeichert werden. Bitte versuchen Sie es erneut.",
      changed: "Dieses Budget wurde geändert, seit Sie es geöffnet haben.",
      reload: "Neueste Version laden",
      archiveTitle: "Budget archivieren",
      archiveDescription:
        "Dieses Budget wird aus den aktiven Plänen entfernt, sein Verlauf bleibt jedoch erhalten. Es werden keine Transaktionen oder Kontostände geändert.",
      archiving: "Wird archiviert…",
      archiveError:
        "Das Budget konnte nicht archiviert werden. Bitte versuchen Sie es erneut.",
    },
    title: "Pläne",
    subtitle: "Planen Sie Ihre Budgets und Sparziele mit Klarheit.",
    budgets: "Budgets",
    all: "Alle",
    goals: "Ziele",
    forecasts: "Prognosen",
    rules: "Regeln",
    askPace: "Pace fragen",
    newPlan: "Neuer Plan",
    monthlyBudgets: "Monatliche Budgets",
    monthlyBudgetsSubtitle:
      "Verfolgen Sie Ihre Ausgaben nach Kategorie in diesem Monat.",
    budgeted: "Budgetiert",
    spent: "Ausgegeben",
    remaining: "Verbleibend",
    used: "% verwendet",
    overall: "Gesamtausgaben",
    status: "Status",
    onTrack: "Im Plan",
    attention: "Achtung",
    overBudget: "Budget überschritten",
    inactive: "Inaktiv",
    savings: "Sparziele",
    savingsSubtitle: "Bringen Sie Ihre Projekte schneller voran.",
    seeAll: "Alle anzeigen",
    target: "Ziel",
    saved: "gespart",
    left: "übrig",
    targetDate: "Zieldatum",
    budgetEmpty: "Keine aktiven Budgets für diesen Zeitraum.",
    savingsEmpty: "Noch keine Sparziele.",
    planInsights: "Planübersicht",
    insightOverBudget: "Ein Budget braucht Aufmerksamkeit",
    insightAttention: "Eine Kategorie nähert sich ihrem Budget",
    insightOnTrack: "Ihre Budgets liegen im Plan",
    unavailable: "Dieser Bereich ist noch nicht verfügbar.",
    loading: "Plan wird aktualisiert…",
    progress: "Budgetfortschritt",
    timeline: "Ausgaben im Zeitverlauf",
    transactions: "Budgettransaktionen",
    insights: "Budgeteinblicke",
    details: "Budgetdetails",
    emptyTransactions: "Noch keine berücksichtigten Transaktionen.",
    more: "Weitere Optionen",
    actualSpending: "Tatsächlich gebuchte Ausgaben",
    period: "Zeitraum",
    category: "Kategorie",
    goalDetail: {
      back: "Zurück zu Plänen",
      targetAmount: "Zielbetrag",
      contributed: "Gespart",
      progressPercent: "Fortschritt",
      completed: "Abgeschlossen",
      active: "Aktiv",
      paused: "Pausiert",
      archived: "Archiviert",
      progress: "Zielfortschritt",
      remaining: "verbleibend",
      history: "Fortschritt im Zeitverlauf",
      historyEmpty: "Ein Fortschrittsverlauf ist noch nicht verfügbar.",
      contributions: "Beitragsverlauf",
      contributionsEmpty:
        "Für dieses Ziel ist kein kanonischer Beitragsverlauf verfügbar.",
      addContribution: "Beitrag hinzufügen",
      addingContribution: "Wird hinzugefügt…",
      contributionHelper: "Dies aktualisiert nur Ihren Zielfortschritt. Es wird kein Geld automatisch bewegt.",
      amount: "Betrag",
      effectiveDate: "Wirksamkeitsdatum",
      invalidEffectiveDate: "Geben Sie ein gültiges Wirksamkeitsdatum ein.",
      noteOptional: "Notiz (optional)",
      contributionInvalid: "Geben Sie einen Betrag größer als null ein und prüfen Sie das Wirksamkeitsdatum.",
      contributionUnavailable: "Dieses Ziel ist nicht mehr für Beiträge verfügbar.",
      contributionError: "Dieser Beitrag konnte nicht hinzugefügt werden. Bitte versuchen Sie es erneut.",
      contribution: "Beitrag",
      reversal: "Stornierung",
      insights: "Zieleinblicke",
      details: "Zieldetails",
      created: "Erstellt",
      currency: "Währung",
      daysRemaining: "{days} Tage verbleibend",
      requiredDaily: "Erforderliches Tagesziel",
      targetDate: "Zieldatum",
      noTargetDate: "Kein Zieldatum",
      completedDescription: "Dieses Ziel hat seinen Zielbetrag erreicht.",
      more: "Weitere Optionen",
      status: "Status",
      cancel: "Abbrechen",
      edit: "Ziel bearbeiten",
      archive: "Ziel archivieren",
      complete: "Ziel abschließen",
      editTitle: "Sparziel bearbeiten",
      editDescription: "Aktualisieren Sie die Planungsdetails dieses Ziels.",
      save: "Änderungen speichern",
      saving: "Wird gespeichert…",
      editError: "Ihre Änderungen konnten nicht gespeichert werden. Bitte versuchen Sie es erneut.",
      archiveTitle: "Sparziel archivieren",
      archiveDescription: "Dieses Ziel verlässt die aktiven Pläne. Fortschritt und Verlauf bleiben erhalten. Es wird kein Geld bewegt und keine Transaktion gelöscht.",
      archiving: "Wird archiviert…",
      archiveError: "Dieses Ziel konnte nicht archiviert werden. Bitte versuchen Sie es erneut.",
      completeTitle: "Sparziel abschließen",
      completeDescription: "Dies ist nur ein Planungsstatus. Es bewegt kein Geld, erstellt keine Transaktion, überträgt keine Mittel und ändert keine Kontostände.",
      completing: "Wird abgeschlossen…",
      completeError: "Dieses Ziel konnte nicht abgeschlossen werden. Bitte versuchen Sie es erneut.",
      changed: "Dieses Ziel wurde geändert, seit Sie es geöffnet haben.",
      reload: "Neueste Version laden",
    },
  },
};

export function getPlansUiLabels(language: "en" | "fr" | "de"): PlansUiLabels {
  return labels[language];
}
