export type PlansUiLabels = {
  readonly createBudget: Readonly<Record<string, string>>;
  readonly budgetManagement: Readonly<Record<string, string>>;
  readonly title: string;
  readonly subtitle: string;
  readonly budgets: string;
  readonly all: string;
  readonly goals: string;
  readonly forecasts: string;
  readonly rules: string;
  readonly askPace: string;
  readonly newPlan: string;
  readonly monthlyBudgets: string;
  readonly monthlyBudgetsSubtitle: string;
  readonly budgeted: string;
  readonly spent: string;
  readonly remaining: string;
  readonly used: string;
  readonly overall: string;
  readonly status: string;
  readonly onTrack: string;
  readonly attention: string;
  readonly overBudget: string;
  readonly inactive: string;
  readonly savings: string;
  readonly savingsSubtitle: string;
  readonly seeAll: string;
  readonly target: string;
  readonly saved: string;
  readonly left: string;
  readonly targetDate: string;
  readonly budgetEmpty: string;
  readonly savingsEmpty: string;
  readonly planInsights: string;
  readonly insightOverBudget: string;
  readonly insightAttention: string;
  readonly insightOnTrack: string;
  readonly unavailable: string;
  readonly loading: string;
  readonly progress: string;
  readonly timeline: string;
  readonly transactions: string;
  readonly insights: string;
  readonly details: string;
  readonly emptyTransactions: string;
  readonly more: string;
  readonly actualSpending: string;
  readonly period: string;
  readonly category: string;
  readonly goalDetail: Readonly<Record<string, string>>;
};

const createBudgetLabels = {
  close: "Close",
  title: "New budget",
  subtitle: "Set a spending limit for a category and track your progress.",
  basicInfo: "Basic info",
  budgetName: "Budget name",
  budgetNameValue: "Food & dining",
  budgetNameHint: "Choose a clear name for this budget.",
  iconAndColour: "Icon and colour",
  iconPicker: "Budget icon",
  iconFood: "Food",
  iconTransport: "Transport",
  iconShopping: "Shopping",
  iconHome: "Home",
  iconHealth: "Health",
  iconEntertainment: "Entertainment",
  iconSubscriptions: "Subscriptions",
  iconBills: "Bills",
  iconEducation: "Education",
  iconTravel: "Travel",
  iconOther: "Other",
  description: "Description",
  optional: "(optional)",
  descriptionValue: "Restaurants, groceries, cafés and get-togethers…",
  categoryScope: "Category & scope",
  mainCategory: "Main category",
  category: "Category",
  scope: "Scope",
  entireCategory: "Entire category",
  selectedSubcategories: "Selected subcategories",
  subcategories: "Subcategories",
  selectCategory: "Select category",
  selectSubcategories: "Select subcategories",
  subcategoriesHint: "Leave blank to include the entire category.",
  noSubcategoriesAvailable: "No subcategories available",
  loadingCategories: "Loading categories…",
  categoryLoadError: "Categories could not be loaded. Please try again.",
  removeSubcategory: "Remove subcategory",
  subcategoriesValue: "Restaurants · Groceries · Cafés",
  amountPeriod: "Amount & period",
  budgetAmount: "Budget amount",
  amountValue: "120,000",
  currency: "FCFA",
  period: "Period",
  monthly: "Monthly",
  weekly: "Weekly",
  custom: "Custom",
  periodValue: "September 2026",
  amountHint: "Maximum amount to spend for this period.",
  selectPeriod: "Select period",
  invalidAmount: "Enter an amount greater than zero.",
  invalidPeriod: "Select a valid period.",
  advancedOptions: "Advanced options",
  monthlyResetTitle: "Monthly reset",
  monthlyResetHint: "This budget starts fresh on the first day of each month.",
  preview: "Preview",
  previewDescription: "Restaurants, groceries, cafés…",
  previewCategoryFallback: "No category selected",
  previewAmountFallback: "No amount set",
  previewPeriodFallback: "No period selected",
  notStarted: "Not started",
  amount: "Amount",
  progressExample: "Progress example",
  notice:
    "This budget will begin on {startsOn} and reset automatically on {resetsOn}.",
  cancel: "Cancel",
  create: "Create budget",
  creating: "Creating…",
  invalidCategory: "Select a valid category.",
  invalidCurrency: "This currency is not available for this workspace.",
  createError: "We could not create this budget. Please try again.",
};

const budgetManagementLabels = {
  edit: "Edit budget",
  archive: "Archive budget",
  editTitle: "Edit budget",
  editDescription: "Update the planning details for this budget.",
  overall: "Overall spending",
  archived: "Archived",
  save: "Save changes",
  saving: "Saving…",
  editError: "We could not save your changes. Please try again.",
  changed: "This budget changed since you opened it.",
  reload: "Reload latest",
  archiveTitle: "Archive budget",
  archiveDescription:
    "This budget will be removed from active plans, but its history will be preserved. No transactions or balances will be changed.",
  archiving: "Archiving…",
  archiveError: "We could not archive this budget. Please try again.",
};

const labels: Record<"en" | "fr" | "de", PlansUiLabels> = {
  en: {
    createBudget: createBudgetLabels,
    budgetManagement: budgetManagementLabels,
    title: "Plans",
    subtitle: "Plan your budgets and savings goals with clarity.",
    budgets: "Budgets",
    all: "All",
    goals: "Goals",
    forecasts: "Forecasts",
    rules: "Rules",
    askPace: "Ask Pace",
    newPlan: "New plan",
    monthlyBudgets: "Monthly budgets",
    monthlyBudgetsSubtitle: "Track your category spending this month.",
    budgeted: "Budgeted",
    spent: "Spent",
    remaining: "Remaining",
    used: "% used",
    overall: "Overall spending",
    status: "Status",
    onTrack: "On track",
    attention: "Attention",
    overBudget: "Over budget",
    inactive: "Inactive",
    savings: "Savings goals",
    savingsSubtitle: "Move your projects forward faster.",
    seeAll: "See all",
    target: "Target",
    saved: "saved",
    left: "left",
    targetDate: "Target date",
    budgetEmpty: "No active budgets for this period.",
    savingsEmpty: "No savings goals yet.",
    planInsights: "Plan insights",
    insightOverBudget: "A budget needs attention",
    insightAttention: "A category is nearing its budget",
    insightOnTrack: "Your budgets are on track",
    unavailable: "This section is not available yet.",
    loading: "Updating plan…",
    progress: "Budget progress",
    timeline: "Spending over time",
    transactions: "Budget transactions",
    insights: "Budget insights",
    details: "Budget details",
    emptyTransactions: "No contributing transactions yet.",
    more: "More options",
    actualSpending: "Actual posted spending",
    period: "Period",
    category: "Category",
    goalDetail: { back: "Back to Plans", targetAmount: "Target amount", contributed: "Saved", progressPercent: "Progress", completed: "Completed", active: "Active", paused: "Paused", archived: "Archived", progress: "Goal progress", remaining: "remaining", history: "Progress over time", historyEmpty: "Progress history is not available yet.", contributions: "Contributions", contributionsEmpty: "No canonical contribution history is available for this goal.", insights: "Goal insights", details: "Goal details", created: "Created", currency: "Currency", daysRemaining: "{days} days remaining", requiredDaily: "Required daily pace", targetDate: "Target date", noTargetDate: "No target date", completedDescription: "This goal has reached its target.", more: "More options", status: "Status" },
  },
  fr: {
    createBudget: {
      close: "Fermer",
      title: "Nouveau budget",
      subtitle: "Fixez une limite pour une catégorie et suivez vos progrès.",
      basicInfo: "Informations générales",
      budgetName: "Nom du budget",
      budgetNameValue: "Alimentation et sorties",
      budgetNameHint: "Choisissez un nom clair pour ce budget.",
      iconAndColour: "Icône et couleur",
      iconPicker: "Icône du budget",
      iconFood: "Alimentation",
      iconTransport: "Transport",
      iconShopping: "Achats",
      iconHome: "Logement",
      iconHealth: "Santé",
      iconEntertainment: "Divertissement",
      iconSubscriptions: "Abonnements",
      iconBills: "Factures",
      iconEducation: "Éducation",
      iconTravel: "Voyages",
      iconOther: "Autre",
      description: "Description",
      optional: "(facultatif)",
      descriptionValue: "Restaurants, courses, cafés et sorties…",
      categoryScope: "Catégorie et portée",
      mainCategory: "Catégorie principale",
      budgetAmount: "Montant du budget",
      period: "Période",
      amountHint: "Montant maximal à dépenser pour cette période.",
      selectPeriod: "Sélectionner une période",
      invalidAmount: "Saisissez un montant supérieur à zéro.",
      invalidPeriod: "Sélectionnez une période valide.",
      category: "Catégorie",
      scope: "Portée",
      entireCategory: "Toute la catégorie",
      selectedSubcategories: "Sous-catégories sélectionnées",
      subcategories: "Sous-catégories",
      selectCategory: "Sélectionner une catégorie",
      selectSubcategories: "Sélectionner des sous-catégories",
      subcategoriesHint: "Laissez vide pour inclure toute la catégorie.",
      noSubcategoriesAvailable: "Aucune sous-catégorie disponible",
      loadingCategories: "Chargement des catégories…",
      categoryLoadError:
        "Les catégories n’ont pas pu être chargées. Veuillez réessayer.",
      removeSubcategory: "Supprimer la sous-catégorie",
      advancedOptions: "Options avancées",
      monthlyResetTitle: "Réinitialisation mensuelle",
      monthlyResetHint:
        "Ce budget recommence à zéro le premier jour de chaque mois.",
      preview: "Aperçu",
      previewDescription: "Restaurants, courses, cafés…",
      previewCategoryFallback: "Aucune catégorie sélectionnée",
      previewAmountFallback: "Aucun montant défini",
      previewPeriodFallback: "Aucune période sélectionnée",
      notStarted: "Pas encore commencé",
      amount: "Montant",
      progressExample: "Exemple de progression",
      notice:
        "Ce budget commencera le {startsOn} et se réinitialisera automatiquement le {resetsOn}.",
      cancel: "Annuler",
      create: "Créer le budget",
      creating: "Création…",
      invalidCategory: "Sélectionnez une catégorie valide.",
      invalidCurrency:
        "Cette devise n’est pas disponible pour cet espace de travail.",
      createError: "Impossible de créer ce budget. Veuillez réessayer.",
    },
    budgetManagement: {
      edit: "Modifier le budget",
      archive: "Archiver le budget",
      editTitle: "Modifier le budget",
      editDescription:
        "Mettez à jour les informations de planification de ce budget.",
      overall: "Dépenses globales",
      archived: "Archivé",
      save: "Enregistrer les modifications",
      saving: "Enregistrement…",
      editError:
        "Impossible d’enregistrer vos modifications. Veuillez réessayer.",
      changed: "Ce budget a changé depuis son ouverture.",
      reload: "Recharger la dernière version",
      archiveTitle: "Archiver le budget",
      archiveDescription:
        "Ce budget sera retiré des plans actifs, mais son historique sera conservé. Aucune transaction ni aucun solde ne seront modifiés.",
      archiving: "Archivage…",
      archiveError: "Impossible d’archiver ce budget. Veuillez réessayer.",
    },
    title: "Plans",
    subtitle: "Planifiez vos budgets et objectifs d’épargne en toute clarté.",
    budgets: "Budgets",
    all: "Tout",
    goals: "Objectifs",
    forecasts: "Prévisions",
    rules: "Règles",
    askPace: "Demander à Pace",
    newPlan: "Nouveau plan",
    monthlyBudgets: "Budgets mensuels",
    monthlyBudgetsSubtitle:
      "Suivez vos dépenses par catégorie pour ce mois-ci.",
    budgeted: "Budgété",
    spent: "Dépensé",
    remaining: "Restant",
    used: "% utilisé",
    overall: "Dépenses globales",
    status: "Statut",
    onTrack: "Sur la bonne voie",
    attention: "Attention",
    overBudget: "Budget dépassé",
    inactive: "Inactif",
    savings: "Objectifs d’épargne",
    savingsSubtitle: "Avancez vers vos projets plus rapidement.",
    seeAll: "Tout voir",
    target: "Objectif",
    saved: "épargnés",
    left: "restant",
    targetDate: "Date cible",
    budgetEmpty: "Aucun budget actif pour cette période.",
    savingsEmpty: "Aucun objectif d’épargne pour le moment.",
    planInsights: "Aperçus du plan",
    insightOverBudget: "Un budget demande votre attention",
    insightAttention: "Une catégorie approche de son budget",
    insightOnTrack: "Vos budgets sont sur la bonne voie",
    unavailable: "Cette section n’est pas encore disponible.",
    loading: "Mise à jour du plan…",
    progress: "Progression du budget",
    timeline: "Dépenses dans le temps",
    transactions: "Transactions de ce budget",
    insights: "Aperçus du budget",
    details: "Détails du budget",
    emptyTransactions: "Aucune transaction contributrice pour le moment.",
    more: "Plus d’options",
    actualSpending: "Dépenses comptabilisées réelles",
    period: "Période",
    category: "Catégorie",
    goalDetail: { back: "Retour aux plans", targetAmount: "Montant cible", contributed: "Épargné", progressPercent: "Progression", completed: "Terminé", active: "Actif", paused: "En pause", archived: "Archivé", progress: "Progression de l’objectif", remaining: "restant", history: "Progression dans le temps", historyEmpty: "L’historique de progression n’est pas encore disponible.", contributions: "Contributions", contributionsEmpty: "Aucun historique de contributions canonique n’est disponible pour cet objectif.", insights: "Aperçus de l’objectif", details: "Détails de l’objectif", created: "Créé", currency: "Devise", daysRemaining: "{days} jours restants", requiredDaily: "Rythme quotidien requis", targetDate: "Date cible", noTargetDate: "Aucune date cible", completedDescription: "Cet objectif a atteint son montant cible.", more: "Plus d’options", status: "Statut" },
  },
  de: {
    createBudget: {
      close: "Schließen",
      title: "Neues Budget",
      subtitle:
        "Legen Sie ein Ausgabenlimit für eine Kategorie fest und verfolgen Sie Ihren Fortschritt.",
      basicInfo: "Grundinformationen",
      budgetName: "Budgetname",
      budgetNameValue: "Essen und Ausgehen",
      budgetNameHint: "Wählen Sie einen eindeutigen Namen für dieses Budget.",
      iconAndColour: "Symbol und Farbe",
      iconPicker: "Budgetsymbol",
      iconFood: "Lebensmittel",
      iconTransport: "Transport",
      iconShopping: "Einkäufe",
      iconHome: "Wohnen",
      iconHealth: "Gesundheit",
      iconEntertainment: "Unterhaltung",
      iconSubscriptions: "Abonnements",
      iconBills: "Rechnungen",
      iconEducation: "Bildung",
      iconTravel: "Reisen",
      iconOther: "Sonstiges",
      description: "Beschreibung",
      optional: "(optional)",
      descriptionValue: "Restaurants, Lebensmittel, Cafés und Treffen…",
      categoryScope: "Kategorie und Umfang",
      mainCategory: "Hauptkategorie",
      budgetAmount: "Budgetbetrag",
      period: "Zeitraum",
      amountHint: "Maximaler Betrag für diesen Zeitraum.",
      selectPeriod: "Zeitraum auswählen",
      invalidAmount: "Geben Sie einen Betrag größer als null ein.",
      invalidPeriod: "Wählen Sie einen gültigen Zeitraum aus.",
      category: "Kategorie",
      scope: "Umfang",
      entireCategory: "Gesamte Kategorie",
      selectedSubcategories: "Ausgewählte Unterkategorien",
      subcategories: "Unterkategorien",
      selectCategory: "Kategorie auswählen",
      selectSubcategories: "Unterkategorien auswählen",
      subcategoriesHint:
        "Leer lassen, um die gesamte Kategorie einzuschließen.",
      noSubcategoriesAvailable: "Keine Unterkategorien verfügbar",
      loadingCategories: "Kategorien werden geladen…",
      categoryLoadError:
        "Kategorien konnten nicht geladen werden. Bitte versuchen Sie es erneut.",
      removeSubcategory: "Unterkategorie entfernen",
      advancedOptions: "Erweiterte Optionen",
      monthlyResetTitle: "Monatliche Zurücksetzung",
      monthlyResetHint: "Dieses Budget beginnt am ersten Tag jedes Monats neu.",
      preview: "Vorschau",
      previewDescription: "Restaurants, Lebensmittel, Cafés…",
      previewCategoryFallback: "Keine Kategorie ausgewählt",
      previewAmountFallback: "Kein Betrag festgelegt",
      previewPeriodFallback: "Kein Zeitraum ausgewählt",
      notStarted: "Noch nicht begonnen",
      amount: "Betrag",
      progressExample: "Fortschrittsbeispiel",
      notice:
        "Dieses Budget beginnt am {startsOn} und wird am {resetsOn} automatisch zurückgesetzt.",
      cancel: "Abbrechen",
      create: "Budget erstellen",
      creating: "Wird erstellt…",
      invalidCategory: "Wählen Sie eine gültige Kategorie aus.",
      invalidCurrency:
        "Diese Währung ist für diesen Arbeitsbereich nicht verfügbar.",
      createError:
        "Dieses Budget konnte nicht erstellt werden. Bitte versuchen Sie es erneut.",
    },
    budgetManagement: {
      edit: "Budget bearbeiten",
      archive: "Budget archivieren",
      editTitle: "Budget bearbeiten",
      editDescription: "Aktualisieren Sie die Planungsdetails dieses Budgets.",
      overall: "Gesamtausgaben",
      archived: "Archiviert",
      save: "Änderungen speichern",
      saving: "Wird gespeichert…",
      editError:
        "Ihre Änderungen konnten nicht gespeichert werden. Bitte versuchen Sie es erneut.",
      changed: "Dieses Budget wurde geändert, seit Sie es geöffnet haben.",
      reload: "Neueste Version laden",
      archiveTitle: "Budget archivieren",
      archiveDescription:
        "Dieses Budget wird aus den aktiven Plänen entfernt, sein Verlauf bleibt jedoch erhalten. Es werden keine Transaktionen oder Kontostände geändert.",
      archiving: "Wird archiviert…",
      archiveError:
        "Das Budget konnte nicht archiviert werden. Bitte versuchen Sie es erneut.",
    },
    title: "Pläne",
    subtitle: "Planen Sie Ihre Budgets und Sparziele mit Klarheit.",
    budgets: "Budgets",
    all: "Alle",
    goals: "Ziele",
    forecasts: "Prognosen",
    rules: "Regeln",
    askPace: "Pace fragen",
    newPlan: "Neuer Plan",
    monthlyBudgets: "Monatliche Budgets",
    monthlyBudgetsSubtitle:
      "Verfolgen Sie Ihre Ausgaben nach Kategorie in diesem Monat.",
    budgeted: "Budgetiert",
    spent: "Ausgegeben",
    remaining: "Verbleibend",
    used: "% verwendet",
    overall: "Gesamtausgaben",
    status: "Status",
    onTrack: "Im Plan",
    attention: "Achtung",
    overBudget: "Budget überschritten",
    inactive: "Inaktiv",
    savings: "Sparziele",
    savingsSubtitle: "Bringen Sie Ihre Projekte schneller voran.",
    seeAll: "Alle anzeigen",
    target: "Ziel",
    saved: "gespart",
    left: "übrig",
    targetDate: "Zieldatum",
    budgetEmpty: "Keine aktiven Budgets für diesen Zeitraum.",
    savingsEmpty: "Noch keine Sparziele.",
    planInsights: "Planübersicht",
    insightOverBudget: "Ein Budget braucht Aufmerksamkeit",
    insightAttention: "Eine Kategorie nähert sich ihrem Budget",
    insightOnTrack: "Ihre Budgets liegen im Plan",
    unavailable: "Dieser Bereich ist noch nicht verfügbar.",
    loading: "Plan wird aktualisiert…",
    progress: "Budgetfortschritt",
    timeline: "Ausgaben im Zeitverlauf",
    transactions: "Budgettransaktionen",
    insights: "Budgeteinblicke",
    details: "Budgetdetails",
    emptyTransactions: "Noch keine berücksichtigten Transaktionen.",
    more: "Weitere Optionen",
    actualSpending: "Tatsächlich gebuchte Ausgaben",
    period: "Zeitraum",
    category: "Kategorie",
    goalDetail: { back: "Zurück zu Plänen", targetAmount: "Zielbetrag", contributed: "Gespart", progressPercent: "Fortschritt", completed: "Abgeschlossen", active: "Aktiv", paused: "Pausiert", archived: "Archiviert", progress: "Zielfortschritt", remaining: "verbleibend", history: "Fortschritt im Zeitverlauf", historyEmpty: "Ein Fortschrittsverlauf ist noch nicht verfügbar.", contributions: "Beiträge", contributionsEmpty: "Für dieses Ziel ist kein kanonischer Beitragsverlauf verfügbar.", insights: "Zieleinblicke", details: "Zieldetails", created: "Erstellt", currency: "Währung", daysRemaining: "{days} Tage verbleibend", requiredDaily: "Erforderliches Tagesziel", targetDate: "Zieldatum", noTargetDate: "Kein Zieldatum", completedDescription: "Dieses Ziel hat seinen Zielbetrag erreicht.", more: "Weitere Optionen", status: "Status" },
  },
};

export function getPlansUiLabels(language: "en" | "fr" | "de"): PlansUiLabels {
  return labels[language];
}
