import type { DashboardLanguage } from "@/i18n/dashboard-messages";

const en = {
  plans: "Plans",
  title: "Rules",
  subtitle: "Automate how Pace organizes and handles your transactions.",
  searchLabel: "Search rules",
  searchPlaceholder: "Search rules…",
  statusFilter: "Status",
  statusALL: "All statuses",
  statusACTIVE: "Active",
  statusPAUSED: "Paused",
  statusARCHIVED: "Archived",
  newRule: "New rule",
  newRuleSoon: "The rule builder is coming soon.",
  kpiTotal: "Total rules",
  kpiActive: "Active rules",
  kpiApplied: "Applied this month",
  kpiReview: "Sent for review this month",
  colRule: "Rule",
  colTrigger: "Trigger",
  colAction: "Action",
  colStatus: "Status",
  colPriority: "Priority",
  colApplied: "Applied",
  colLastApplied: "Last applied",
  appliedCount: "{count} applied",
  neverApplied: "Not applied yet",
  loading: "Updating rules…",
  emptyTitle: "No rules yet",
  emptyDescription:
    "Rules automatically categorize new transactions or send them to your inbox for review.",
  noResultsTitle: "No matching rules",
  noResultsDescription: "Try another search or status.",
  clearFilters: "Clear filters",
  details: "Rule details",
  trigger: "Trigger",
  triggerEvent: "When a transaction is created",
  conditions: "Conditions",
  noConditions: "No additional conditions",
  action: "Action",
  priority: "Priority",
  created: "Created",
  lastUpdated: "Last updated",
  byYou: "{date} by you",
  byPace: "{date} by Pace",
  byMember: "{date} by a workspace member",
  recentExecutions: "Recent executions",
  noExecutions: "This rule hasn't run on any transaction yet.",
  back: "Back to rules",
  fieldTRANSACTION_KIND: "Transaction kind",
  fieldENTRY_ORIGIN: "Source",
  fieldACCOUNT: "Account",
  fieldCATEGORY: "Category",
  fieldCOUNTERPARTY: "Merchant",
  fieldNOTE: "Note",
  opEQUALS: "is exactly",
  opCONTAINS: "contains",
  opSTARTS_WITH: "starts with",
  opIS_EMPTY: "is empty",
  opIS_NOT_EMPTY: "is not empty",
  opIS_ONE_OF: "is",
  opIS_NOT_ONE_OF: "is not",
  kindEXPENSE: "Expense",
  kindINCOME: "Income",
  kindTRANSFER: "Transfer",
  kindREFUND: "Refund",
  originMANUAL: "Manual entry",
  originIMPORT: "Import",
  originAGENT: "Pace",
  originOTHER: "Other",
  actionASSIGN_CATEGORY: "Set category",
  actionROUTE_FOR_REVIEW: "Send to inbox",
  needsReview: "Needs review",
  unavailableReference: "Unavailable",
  unknownTransaction: "Transaction",
  outcomeAPPLIED_ASSIGN_CATEGORY: "Categorized",
  outcomeAPPLIED_ROUTE_FOR_REVIEW: "Sent for review",
  outcomeSKIPPED: "Skipped",
  outcomeSHADOWED: "Overridden",
  outcomeFAILED: "Failed",
  outcomePENDING: "Pending",
  enable: "Enable",
  disable: "Disable",
  enabling: "Enabling…",
  disabling: "Disabling…",
  more: "More actions",
  archive: "Archive",
  archiveTitle: "Archive this rule?",
  archiveDescription:
    "The rule stops running on new transactions. Its history stays available and no transaction is changed.",
  archiving: "Archiving…",
  cancel: "Cancel",
  changed: "This rule changed since you opened it.",
  reload: "Load latest version",
  actionError: "This rule couldn't be updated. Please try again.",
  errorTitle: "Unable to load rules",
  errorDescription: "We couldn't load your rules right now. Please try again.",
  retry: "Retry",
} as const;

export type RulesUiLabels = { readonly [Key in keyof typeof en]: string };

const fr: RulesUiLabels = {
  plans: "Plans",
  title: "Règles",
  subtitle: "Automatisez la façon dont Pace organise et traite vos transactions.",
  searchLabel: "Rechercher des règles",
  searchPlaceholder: "Rechercher des règles…",
  statusFilter: "Statut",
  statusALL: "Tous les statuts",
  statusACTIVE: "Active",
  statusPAUSED: "En pause",
  statusARCHIVED: "Archivée",
  newRule: "Nouvelle règle",
  newRuleSoon: "L’éditeur de règles arrive bientôt.",
  kpiTotal: "Règles au total",
  kpiActive: "Règles actives",
  kpiApplied: "Appliquées ce mois-ci",
  kpiReview: "Envoyées en revue ce mois-ci",
  colRule: "Règle",
  colTrigger: "Déclencheur",
  colAction: "Action",
  colStatus: "Statut",
  colPriority: "Priorité",
  colApplied: "Appliquée",
  colLastApplied: "Dernière application",
  appliedCount: "{count} application(s)",
  neverApplied: "Pas encore appliquée",
  loading: "Mise à jour des règles…",
  emptyTitle: "Aucune règle pour l’instant",
  emptyDescription:
    "Les règles catégorisent automatiquement les nouvelles transactions ou les envoient dans votre boîte de réception pour revue.",
  noResultsTitle: "Aucune règle correspondante",
  noResultsDescription: "Essayez une autre recherche ou un autre statut.",
  clearFilters: "Effacer les filtres",
  details: "Détails de la règle",
  trigger: "Déclencheur",
  triggerEvent: "Lorsqu’une transaction est créée",
  conditions: "Conditions",
  noConditions: "Aucune condition supplémentaire",
  action: "Action",
  priority: "Priorité",
  created: "Créée",
  lastUpdated: "Dernière modification",
  byYou: "{date} par vous",
  byPace: "{date} par Pace",
  byMember: "{date} par un membre de l’espace",
  recentExecutions: "Exécutions récentes",
  noExecutions: "Cette règle ne s’est encore appliquée à aucune transaction.",
  back: "Retour aux règles",
  fieldTRANSACTION_KIND: "Type de transaction",
  fieldENTRY_ORIGIN: "Source",
  fieldACCOUNT: "Compte",
  fieldCATEGORY: "Catégorie",
  fieldCOUNTERPARTY: "Marchand",
  fieldNOTE: "Note",
  opEQUALS: "est exactement",
  opCONTAINS: "contient",
  opSTARTS_WITH: "commence par",
  opIS_EMPTY: "est vide",
  opIS_NOT_EMPTY: "n’est pas vide",
  opIS_ONE_OF: "est",
  opIS_NOT_ONE_OF: "n’est pas",
  kindEXPENSE: "Dépense",
  kindINCOME: "Revenu",
  kindTRANSFER: "Virement",
  kindREFUND: "Remboursement",
  originMANUAL: "Saisie manuelle",
  originIMPORT: "Import",
  originAGENT: "Pace",
  originOTHER: "Autre",
  actionASSIGN_CATEGORY: "Définir la catégorie",
  actionROUTE_FOR_REVIEW: "Envoyer en boîte de réception",
  needsReview: "À vérifier",
  unavailableReference: "Indisponible",
  unknownTransaction: "Transaction",
  outcomeAPPLIED_ASSIGN_CATEGORY: "Catégorisée",
  outcomeAPPLIED_ROUTE_FOR_REVIEW: "Envoyée en revue",
  outcomeSKIPPED: "Ignorée",
  outcomeSHADOWED: "Remplacée",
  outcomeFAILED: "Échec",
  outcomePENDING: "En attente",
  enable: "Activer",
  disable: "Désactiver",
  enabling: "Activation…",
  disabling: "Désactivation…",
  more: "Plus d’actions",
  archive: "Archiver",
  archiveTitle: "Archiver cette règle ?",
  archiveDescription:
    "La règle ne s’appliquera plus aux nouvelles transactions. Son historique reste disponible et aucune transaction n’est modifiée.",
  archiving: "Archivage…",
  cancel: "Annuler",
  changed: "Cette règle a été modifiée depuis que vous l’avez ouverte.",
  reload: "Charger la dernière version",
  actionError: "Impossible de mettre à jour cette règle. Veuillez réessayer.",
  errorTitle: "Impossible de charger les règles",
  errorDescription: "Nous n’avons pas pu charger vos règles pour le moment. Veuillez réessayer.",
  retry: "Réessayer",
};

const de: RulesUiLabels = {
  plans: "Pläne",
  title: "Regeln",
  subtitle: "Automatisieren Sie, wie Pace Ihre Transaktionen ordnet und behandelt.",
  searchLabel: "Regeln durchsuchen",
  searchPlaceholder: "Regeln durchsuchen…",
  statusFilter: "Status",
  statusALL: "Alle Status",
  statusACTIVE: "Aktiv",
  statusPAUSED: "Pausiert",
  statusARCHIVED: "Archiviert",
  newRule: "Neue Regel",
  newRuleSoon: "Der Regel-Editor ist bald verfügbar.",
  kpiTotal: "Regeln gesamt",
  kpiActive: "Aktive Regeln",
  kpiApplied: "Diesen Monat angewendet",
  kpiReview: "Diesen Monat zur Prüfung gesendet",
  colRule: "Regel",
  colTrigger: "Auslöser",
  colAction: "Aktion",
  colStatus: "Status",
  colPriority: "Priorität",
  colApplied: "Angewendet",
  colLastApplied: "Zuletzt angewendet",
  appliedCount: "{count}× angewendet",
  neverApplied: "Noch nicht angewendet",
  loading: "Regeln werden aktualisiert…",
  emptyTitle: "Noch keine Regeln",
  emptyDescription:
    "Regeln kategorisieren neue Transaktionen automatisch oder senden sie zur Prüfung in Ihren Posteingang.",
  noResultsTitle: "Keine passenden Regeln",
  noResultsDescription: "Versuchen Sie eine andere Suche oder einen anderen Status.",
  clearFilters: "Filter zurücksetzen",
  details: "Regeldetails",
  trigger: "Auslöser",
  triggerEvent: "Wenn eine Transaktion erstellt wird",
  conditions: "Bedingungen",
  noConditions: "Keine weiteren Bedingungen",
  action: "Aktion",
  priority: "Priorität",
  created: "Erstellt",
  lastUpdated: "Zuletzt geändert",
  byYou: "{date} von Ihnen",
  byPace: "{date} von Pace",
  byMember: "{date} von einem Mitglied",
  recentExecutions: "Letzte Ausführungen",
  noExecutions: "Diese Regel wurde noch auf keine Transaktion angewendet.",
  back: "Zurück zu den Regeln",
  fieldTRANSACTION_KIND: "Transaktionsart",
  fieldENTRY_ORIGIN: "Quelle",
  fieldACCOUNT: "Konto",
  fieldCATEGORY: "Kategorie",
  fieldCOUNTERPARTY: "Händler",
  fieldNOTE: "Notiz",
  opEQUALS: "ist genau",
  opCONTAINS: "enthält",
  opSTARTS_WITH: "beginnt mit",
  opIS_EMPTY: "ist leer",
  opIS_NOT_EMPTY: "ist nicht leer",
  opIS_ONE_OF: "ist",
  opIS_NOT_ONE_OF: "ist nicht",
  kindEXPENSE: "Ausgabe",
  kindINCOME: "Einnahme",
  kindTRANSFER: "Überweisung",
  kindREFUND: "Erstattung",
  originMANUAL: "Manuelle Eingabe",
  originIMPORT: "Import",
  originAGENT: "Pace",
  originOTHER: "Sonstige",
  actionASSIGN_CATEGORY: "Kategorie festlegen",
  actionROUTE_FOR_REVIEW: "In den Posteingang senden",
  needsReview: "Prüfung nötig",
  unavailableReference: "Nicht verfügbar",
  unknownTransaction: "Transaktion",
  outcomeAPPLIED_ASSIGN_CATEGORY: "Kategorisiert",
  outcomeAPPLIED_ROUTE_FOR_REVIEW: "Zur Prüfung gesendet",
  outcomeSKIPPED: "Übersprungen",
  outcomeSHADOWED: "Überlagert",
  outcomeFAILED: "Fehlgeschlagen",
  outcomePENDING: "Ausstehend",
  enable: "Aktivieren",
  disable: "Deaktivieren",
  enabling: "Wird aktiviert…",
  disabling: "Wird deaktiviert…",
  more: "Weitere Aktionen",
  archive: "Archivieren",
  archiveTitle: "Diese Regel archivieren?",
  archiveDescription:
    "Die Regel wird nicht mehr auf neue Transaktionen angewendet. Ihr Verlauf bleibt erhalten und keine Transaktion wird geändert.",
  archiving: "Wird archiviert…",
  cancel: "Abbrechen",
  changed: "Diese Regel wurde geändert, seit Sie sie geöffnet haben.",
  reload: "Neueste Version laden",
  actionError: "Diese Regel konnte nicht aktualisiert werden. Bitte versuchen Sie es erneut.",
  errorTitle: "Regeln konnten nicht geladen werden",
  errorDescription: "Ihre Regeln konnten gerade nicht geladen werden. Bitte versuchen Sie es erneut.",
  retry: "Erneut versuchen",
};

const rulesLabels: Readonly<Record<DashboardLanguage, RulesUiLabels>> = { en, fr, de };

export function getRulesUiLabels(language: DashboardLanguage): RulesUiLabels {
  return rulesLabels[language];
}
