import type { DashboardLanguage } from "@/i18n/dashboard-messages";

const en = {
  plans: "Plans",
  title: "Rules",
  subtitle: "Automate how Pace organizes and handles your transactions.",
  searchLabel: "Search rules",
  searchPlaceholder: "Search rules…",
  statusFilter: "Status",
  statusALL: "All statuses",
  statusACTIVE: "Active",
  statusPAUSED: "Paused",
  statusARCHIVED: "Archived",
  newRule: "New rule",
  kpiTotal: "Total rules",
  kpiActive: "Active rules",
  kpiApplied: "Applied this month",
  kpiReview: "Sent for review this month",
  colRule: "Rule",
  colTrigger: "Trigger",
  colAction: "Action",
  colStatus: "Status",
  colPriority: "Priority",
  colApplied: "Applied",
  colLastApplied: "Last applied",
  appliedCount: "{count} applied",
  neverApplied: "Not applied yet",
  loading: "Updating rules…",
  emptyTitle: "No rules yet",
  emptyDescription:
    "Rules automatically categorize new transactions or send them to your inbox for review.",
  noResultsTitle: "No matching rules",
  noResultsDescription: "Try another search or status.",
  clearFilters: "Clear filters",
  details: "Rule details",
  trigger: "Trigger",
  triggerEvent: "When a transaction is created",
  conditions: "Conditions",
  noConditions: "No additional conditions",
  action: "Action",
  priority: "Priority",
  created: "Created",
  lastUpdated: "Last updated",
  byYou: "{date} by you",
  byPace: "{date} by Pace",
  byMember: "{date} by a workspace member",
  recentExecutions: "Recent executions",
  noExecutions: "This rule hasn't run on any transaction yet.",
  back: "Back to rules",
  fieldTRANSACTION_KIND: "Transaction kind",
  fieldENTRY_ORIGIN: "Source",
  fieldACCOUNT: "Account",
  fieldCATEGORY: "Category",
  fieldCOUNTERPARTY: "Merchant",
  fieldNOTE: "Note",
  opEQUALS: "is exactly",
  opCONTAINS: "contains",
  opSTARTS_WITH: "starts with",
  opIS_EMPTY: "is empty",
  opIS_NOT_EMPTY: "is not empty",
  opIS_ONE_OF: "is",
  opIS_NOT_ONE_OF: "is not",
  kindEXPENSE: "Expense",
  kindINCOME: "Income",
  kindTRANSFER: "Transfer",
  kindREFUND: "Refund",
  originMANUAL: "Manual entry",
  originIMPORT: "Import",
  originAGENT: "Pace",
  originOTHER: "Other",
  actionASSIGN_CATEGORY: "Set category",
  actionROUTE_FOR_REVIEW: "Send to inbox",
  needsReview: "Needs review",
  unavailableReference: "Unavailable",
  unknownTransaction: "Transaction",
  outcomeAPPLIED_ASSIGN_CATEGORY: "Categorized",
  outcomeAPPLIED_ROUTE_FOR_REVIEW: "Sent for review",
  outcomeSKIPPED: "Skipped",
  outcomeSHADOWED: "Overridden",
  outcomeFAILED: "Failed",
  outcomePENDING: "Pending",
  enable: "Enable",
  disable: "Disable",
  enabling: "Enabling…",
  disabling: "Disabling…",
  more: "More actions",
  archive: "Archive",
  archiveTitle: "Archive this rule?",
  archiveDescription:
    "The rule stops running on new transactions. Its history stays available and no transaction is changed.",
  archiving: "Archiving…",
  cancel: "Cancel",
  changed: "This rule changed since you opened it.",
  reload: "Load latest version",
  actionError: "This rule couldn't be updated. Please try again.",
  errorTitle: "Unable to load rules",
  errorDescription: "We couldn't load your rules right now. Please try again.",
  retry: "Retry",
  edit: "Edit",
  newRuleTitle: "Create a new rule",
  editRuleTitle: "Edit rule",
  builderSubtitleTRIGGER: "Choose when this rule should apply.",
  builderSubtitleCONDITIONS: "Add conditions to make your rule more specific.",
  builderSubtitleACTION: "Choose what Pace does when the rule matches.",
  builderSubtitleREVIEW: "Check your rule and test it on recent transactions before saving.",
  stepper: "Rule steps",
  stepProgress: "Step {current} of {total}",
  stepCompleted: "Completed",
  stepCurrent: "Current step",
  stepTRIGGER: "Trigger",
  stepHintTRIGGER: "When to apply",
  stepCONDITIONS: "Conditions",
  stepHintCONDITIONS: "Refine the match",
  stepACTION: "Action",
  stepHintACTION: "What to do",
  stepREVIEW: "Review",
  stepHintREVIEW: "Confirm rule",
  presetMERCHANT_CONTAINS: "Merchant contains",
  presetHintMERCHANT_CONTAINS: "When the merchant or source name contains specific text",
  presetMERCHANT_EQUALS: "Merchant is exactly",
  presetHintMERCHANT_EQUALS: "When the merchant or source name matches exactly",
  presetMERCHANT_EMPTY: "Merchant is empty",
  presetHintMERCHANT_EMPTY: "When the transaction has no merchant",
  presetACCOUNT_IS: "Account is",
  presetHintACCOUNT_IS: "When the transaction is from a specific account",
  presetTRANSACTION_KIND_IS: "Transaction kind",
  presetHintTRANSACTION_KIND_IS: "When the transaction is an expense, income, transfer or refund",
  presetNOTE_CONTAINS: "Note contains",
  presetHintNOTE_CONTAINS: "When the transaction note contains specific text",
  presetCATEGORY_EMPTY: "Uncategorized",
  presetHintCATEGORY_EMPTY: "When the transaction has no category yet",
  presetSOURCE_IS: "Source is",
  presetHintSOURCE_IS: "When the transaction was entered manually, imported or added by Pace",
  triggerEventHint: "Rules run on new transactions after they are created.",
  field: "Field",
  operator: "Operator",
  value: "Value",
  valuePlaceholder: "e.g. orange money",
  noOptions: "No options available.",
  conditionsTitle: "Set conditions (optional)",
  conditionNumber: "Condition {index}",
  removeCondition: "Remove condition {index}",
  addCondition: "Add condition",
  noExtraConditions: "No extra conditions. The rule applies whenever the trigger matches.",
  allConditionsHint: "The trigger and every condition must match.",
  actionTitle: "Choose an action",
  actionHintASSIGN_CATEGORY: "Set a category on uncategorized expenses and income",
  actionHintROUTE_FOR_REVIEW: "Send the transaction to your inbox for review",
  category: "Category",
  selectCategory: "Select a category",
  noMoneyMovement: "Rules never move money, create transactions or change amounts.",
  reviewTitle: "Review your rule",
  ruleName: "Rule name",
  ruleNameHint: "Shown in your rules list.",
  priorityHint: "1 runs first. Lower numbers win when rules conflict.",
  priorityHighest: "{priority} (highest)",
  enabledState: "Status",
  enabledOn: "Enabled — runs on new transactions",
  enabledOff: "Disabled — saved but won’t run",
  enableAfterSave: "Enable this rule after saving",
  editEnabledHint: "Use Enable or Disable on the rule to change its status.",
  dryRunTitle: "Test your rule",
  dryRunSubtitle: "See how this rule would apply to your {count} most recent transactions.",
  dryRunMatching: "Matching ({count})",
  dryRunNotMatching: "Not matching ({count})",
  dryRunRunning: "Testing rule…",
  dryRunError: "We couldn’t test this rule. You can still save it.",
  dryRunRetry: "Test again",
  dryRunEmptyMatching: "No recent transactions match this rule.",
  dryRunEmptyNotMatching: "Every recent transaction matches this rule.",
  dryRunNoTransactions: "There are no recent transactions to test yet.",
  dryRunNotice: "This is a simulation. No changes will be made to your transactions.",
  dryRunDisabledNotice: "This rule will be saved disabled, so it won’t run until you enable it.",
  dryRunWouldApply: "Would apply",
  dryRunSkipped: "Would be skipped",
  dryRunShadowed: "Overridden by “{name}”",
  dryRunNoMatch: "No match",
  whyMatched: "Why it matched",
  whyNotMatched: "Why it didn’t match",
  conditionMet: "Met",
  conditionNotMet: "Not met",
  transactionValue: "Transaction: {value}",
  emptyValue: "empty",
  reasonTRANSACTION_KIND_NOT_SUPPORTED: "Only expenses and income can be categorized or reviewed",
  reasonTRANSACTION_LOCKED: "This transaction can no longer be edited",
  reasonCATEGORY_ALREADY_SET: "Already has a category",
  reasonCATEGORY_UNAVAILABLE: "Category unavailable",
  reasonCATEGORY_KIND_MISMATCH: "Category doesn’t fit this transaction kind",
  reasonALREADY_IN_REVIEW: "Already in your inbox",
  reasonSHADOWED_BY_HIGHER_PRIORITY_RULE: "A higher-priority rule applies first",
  reasonACTION_FAILED: "Action failed",
  continue: "Continue",
  backStep: "Back",
  createRule: "Create rule",
  saveChanges: "Save changes",
  saving: "Saving…",
  close: "Close",
  fixErrors: "Fix the highlighted fields to continue.",
  errorVALUE_REQUIRED: "Enter a value.",
  errorSELECTION_REQUIRED: "Select at least one option.",
  errorTEXT_TOO_LONG: "Use 160 characters or fewer.",
  errorTOO_MANY_VALUES: "Select 50 options or fewer.",
  errorTOO_MANY_CONDITIONS: "You can use up to 10 conditions.",
  errorCATEGORY_REQUIRED: "Choose a category.",
  errorNAME_REQUIRED: "Give this rule a name.",
  errorNAME_TOO_LONG: "Use 160 characters or fewer.",
  errorPRIORITY_INVALID: "Enter a whole number from 1 to 10,000.",
  saveError: "This rule couldn’t be saved. Please try again.",
  saveInvalid: "Some rule details are no longer valid. Check the category and accounts.",
  staleEdit: "This rule changed since you opened it. Your edits haven’t been saved.",
  previewLabel: "Rule preview",
  selectValues: "Select one or more",
  searchOptions: "Search…",
  triggerOptionsTitle: "Choose a trigger",
  triggerValueTitle: "Refine the match",
  actionTypeLabel: "What should Pace do?",
  nameSectionTitle: "Rule details",
  sentencePending: "Not set yet",
  textMatchHint: "Matching ignores capital letters and extra spaces.",
  categorySearch: "Search categories",
  noCategoryMatch: "No category matches your search.",
} as const;

export type RulesUiLabels = { readonly [Key in keyof typeof en]: string };

const fr: RulesUiLabels = {
  plans: "Plans",
  title: "Règles",
  subtitle: "Automatisez la façon dont Pace organise et traite vos transactions.",
  searchLabel: "Rechercher des règles",
  searchPlaceholder: "Rechercher des règles…",
  statusFilter: "Statut",
  statusALL: "Tous les statuts",
  statusACTIVE: "Active",
  statusPAUSED: "En pause",
  statusARCHIVED: "Archivée",
  newRule: "Nouvelle règle",
  kpiTotal: "Règles au total",
  kpiActive: "Règles actives",
  kpiApplied: "Appliquées ce mois-ci",
  kpiReview: "Envoyées en revue ce mois-ci",
  colRule: "Règle",
  colTrigger: "Déclencheur",
  colAction: "Action",
  colStatus: "Statut",
  colPriority: "Priorité",
  colApplied: "Appliquée",
  colLastApplied: "Dernière application",
  appliedCount: "{count} application(s)",
  neverApplied: "Pas encore appliquée",
  loading: "Mise à jour des règles…",
  emptyTitle: "Aucune règle pour l’instant",
  emptyDescription:
    "Les règles catégorisent automatiquement les nouvelles transactions ou les envoient dans votre boîte de réception pour revue.",
  noResultsTitle: "Aucune règle correspondante",
  noResultsDescription: "Essayez une autre recherche ou un autre statut.",
  clearFilters: "Effacer les filtres",
  details: "Détails de la règle",
  trigger: "Déclencheur",
  triggerEvent: "Lorsqu’une transaction est créée",
  conditions: "Conditions",
  noConditions: "Aucune condition supplémentaire",
  action: "Action",
  priority: "Priorité",
  created: "Créée",
  lastUpdated: "Dernière modification",
  byYou: "{date} par vous",
  byPace: "{date} par Pace",
  byMember: "{date} par un membre de l’espace",
  recentExecutions: "Exécutions récentes",
  noExecutions: "Cette règle ne s’est encore appliquée à aucune transaction.",
  back: "Retour aux règles",
  fieldTRANSACTION_KIND: "Type de transaction",
  fieldENTRY_ORIGIN: "Source",
  fieldACCOUNT: "Compte",
  fieldCATEGORY: "Catégorie",
  fieldCOUNTERPARTY: "Marchand",
  fieldNOTE: "Note",
  opEQUALS: "est exactement",
  opCONTAINS: "contient",
  opSTARTS_WITH: "commence par",
  opIS_EMPTY: "est vide",
  opIS_NOT_EMPTY: "n’est pas vide",
  opIS_ONE_OF: "est",
  opIS_NOT_ONE_OF: "n’est pas",
  kindEXPENSE: "Dépense",
  kindINCOME: "Revenu",
  kindTRANSFER: "Virement",
  kindREFUND: "Remboursement",
  originMANUAL: "Saisie manuelle",
  originIMPORT: "Import",
  originAGENT: "Pace",
  originOTHER: "Autre",
  actionASSIGN_CATEGORY: "Définir la catégorie",
  actionROUTE_FOR_REVIEW: "Envoyer en boîte de réception",
  needsReview: "À vérifier",
  unavailableReference: "Indisponible",
  unknownTransaction: "Transaction",
  outcomeAPPLIED_ASSIGN_CATEGORY: "Catégorisée",
  outcomeAPPLIED_ROUTE_FOR_REVIEW: "Envoyée en revue",
  outcomeSKIPPED: "Ignorée",
  outcomeSHADOWED: "Remplacée",
  outcomeFAILED: "Échec",
  outcomePENDING: "En attente",
  enable: "Activer",
  disable: "Désactiver",
  enabling: "Activation…",
  disabling: "Désactivation…",
  more: "Plus d’actions",
  archive: "Archiver",
  archiveTitle: "Archiver cette règle ?",
  archiveDescription:
    "La règle ne s’appliquera plus aux nouvelles transactions. Son historique reste disponible et aucune transaction n’est modifiée.",
  archiving: "Archivage…",
  cancel: "Annuler",
  changed: "Cette règle a été modifiée depuis que vous l’avez ouverte.",
  reload: "Charger la dernière version",
  actionError: "Impossible de mettre à jour cette règle. Veuillez réessayer.",
  errorTitle: "Impossible de charger les règles",
  errorDescription: "Nous n’avons pas pu charger vos règles pour le moment. Veuillez réessayer.",
  retry: "Réessayer",
  edit: "Modifier",
  newRuleTitle: "Créer une règle",
  editRuleTitle: "Modifier la règle",
  builderSubtitleTRIGGER: "Choisissez quand cette règle doit s’appliquer.",
  builderSubtitleCONDITIONS: "Ajoutez des conditions pour préciser votre règle.",
  builderSubtitleACTION: "Choisissez ce que fait Pace lorsque la règle correspond.",
  builderSubtitleREVIEW: "Vérifiez votre règle et testez-la sur vos transactions récentes avant d’enregistrer.",
  stepper: "Étapes de la règle",
  stepProgress: "Étape {current} sur {total}",
  stepCompleted: "Terminée",
  stepCurrent: "Étape en cours",
  stepTRIGGER: "Déclencheur",
  stepHintTRIGGER: "Quand l’appliquer",
  stepCONDITIONS: "Conditions",
  stepHintCONDITIONS: "Affiner la correspondance",
  stepACTION: "Action",
  stepHintACTION: "Que faire",
  stepREVIEW: "Vérification",
  stepHintREVIEW: "Confirmer la règle",
  presetMERCHANT_CONTAINS: "Le marchand contient",
  presetHintMERCHANT_CONTAINS: "Lorsque le nom du marchand ou de la source contient un texte précis",
  presetMERCHANT_EQUALS: "Le marchand est exactement",
  presetHintMERCHANT_EQUALS: "Lorsque le nom du marchand ou de la source correspond exactement",
  presetMERCHANT_EMPTY: "Le marchand est vide",
  presetHintMERCHANT_EMPTY: "Lorsque la transaction n’a pas de marchand",
  presetACCOUNT_IS: "Le compte est",
  presetHintACCOUNT_IS: "Lorsque la transaction provient d’un compte précis",
  presetTRANSACTION_KIND_IS: "Type de transaction",
  presetHintTRANSACTION_KIND_IS: "Lorsque la transaction est une dépense, un revenu, un virement ou un remboursement",
  presetNOTE_CONTAINS: "La note contient",
  presetHintNOTE_CONTAINS: "Lorsque la note de la transaction contient un texte précis",
  presetCATEGORY_EMPTY: "Sans catégorie",
  presetHintCATEGORY_EMPTY: "Lorsque la transaction n’a pas encore de catégorie",
  presetSOURCE_IS: "La source est",
  presetHintSOURCE_IS: "Lorsque la transaction a été saisie manuellement, importée ou ajoutée par Pace",
  triggerEventHint: "Les règles s’appliquent aux nouvelles transactions après leur création.",
  field: "Champ",
  operator: "Opérateur",
  value: "Valeur",
  valuePlaceholder: "ex. orange money",
  noOptions: "Aucune option disponible.",
  conditionsTitle: "Définir des conditions (facultatif)",
  conditionNumber: "Condition {index}",
  removeCondition: "Supprimer la condition {index}",
  addCondition: "Ajouter une condition",
  noExtraConditions: "Aucune condition supplémentaire. La règle s’applique dès que le déclencheur correspond.",
  allConditionsHint: "Le déclencheur et toutes les conditions doivent correspondre.",
  actionTitle: "Choisir une action",
  actionHintASSIGN_CATEGORY: "Définir une catégorie sur les dépenses et revenus non catégorisés",
  actionHintROUTE_FOR_REVIEW: "Envoyer la transaction dans votre boîte de réception pour revue",
  category: "Catégorie",
  selectCategory: "Sélectionner une catégorie",
  noMoneyMovement: "Les règles ne déplacent jamais d’argent, ne créent pas de transactions et ne modifient pas les montants.",
  reviewTitle: "Vérifier votre règle",
  ruleName: "Nom de la règle",
  ruleNameHint: "Affiché dans votre liste de règles.",
  priorityHint: "1 s’exécute en premier. Le plus petit nombre l’emporte en cas de conflit.",
  priorityHighest: "{priority} (la plus haute)",
  enabledState: "Statut",
  enabledOn: "Activée — s’applique aux nouvelles transactions",
  enabledOff: "Désactivée — enregistrée mais inactive",
  enableAfterSave: "Activer cette règle après l’enregistrement",
  editEnabledHint: "Utilisez Activer ou Désactiver sur la règle pour changer son statut.",
  dryRunTitle: "Tester votre règle",
  dryRunSubtitle: "Voyez comment cette règle s’appliquerait à vos {count} transactions les plus récentes.",
  dryRunMatching: "Correspondantes ({count})",
  dryRunNotMatching: "Non correspondantes ({count})",
  dryRunRunning: "Test de la règle…",
  dryRunError: "Impossible de tester cette règle. Vous pouvez quand même l’enregistrer.",
  dryRunRetry: "Relancer le test",
  dryRunEmptyMatching: "Aucune transaction récente ne correspond à cette règle.",
  dryRunEmptyNotMatching: "Toutes les transactions récentes correspondent à cette règle.",
  dryRunNoTransactions: "Aucune transaction récente à tester pour l’instant.",
  dryRunNotice: "Ceci est une simulation. Aucune modification ne sera apportée à vos transactions.",
  dryRunDisabledNotice: "Cette règle sera enregistrée désactivée et ne s’appliquera pas avant d’être activée.",
  dryRunWouldApply: "S’appliquerait",
  dryRunSkipped: "Serait ignorée",
  dryRunShadowed: "Remplacée par « {name} »",
  dryRunNoMatch: "Aucune correspondance",
  whyMatched: "Pourquoi elle correspond",
  whyNotMatched: "Pourquoi elle ne correspond pas",
  conditionMet: "Remplie",
  conditionNotMet: "Non remplie",
  transactionValue: "Transaction : {value}",
  emptyValue: "vide",
  reasonTRANSACTION_KIND_NOT_SUPPORTED: "Seuls les dépenses et revenus peuvent être catégorisés ou revus",
  reasonTRANSACTION_LOCKED: "Cette transaction ne peut plus être modifiée",
  reasonCATEGORY_ALREADY_SET: "A déjà une catégorie",
  reasonCATEGORY_UNAVAILABLE: "Catégorie indisponible",
  reasonCATEGORY_KIND_MISMATCH: "La catégorie ne convient pas à ce type de transaction",
  reasonALREADY_IN_REVIEW: "Déjà dans votre boîte de réception",
  reasonSHADOWED_BY_HIGHER_PRIORITY_RULE: "Une règle plus prioritaire s’applique d’abord",
  reasonACTION_FAILED: "Échec de l’action",
  continue: "Continuer",
  backStep: "Retour",
  createRule: "Créer la règle",
  saveChanges: "Enregistrer les modifications",
  saving: "Enregistrement…",
  close: "Fermer",
  fixErrors: "Corrigez les champs signalés pour continuer.",
  errorVALUE_REQUIRED: "Saisissez une valeur.",
  errorSELECTION_REQUIRED: "Sélectionnez au moins une option.",
  errorTEXT_TOO_LONG: "Utilisez 160 caractères au maximum.",
  errorTOO_MANY_VALUES: "Sélectionnez 50 options au maximum.",
  errorTOO_MANY_CONDITIONS: "Vous pouvez utiliser jusqu’à 10 conditions.",
  errorCATEGORY_REQUIRED: "Choisissez une catégorie.",
  errorNAME_REQUIRED: "Donnez un nom à cette règle.",
  errorNAME_TOO_LONG: "Utilisez 160 caractères au maximum.",
  errorPRIORITY_INVALID: "Saisissez un nombre entier entre 1 et 10 000.",
  saveError: "Impossible d’enregistrer cette règle. Veuillez réessayer.",
  saveInvalid: "Certains détails de la règle ne sont plus valides. Vérifiez la catégorie et les comptes.",
  staleEdit: "Cette règle a été modifiée depuis que vous l’avez ouverte. Vos modifications n’ont pas été enregistrées.",
  previewLabel: "Aperçu de la règle",
  selectValues: "Sélectionner une ou plusieurs options",
  searchOptions: "Rechercher…",
  triggerOptionsTitle: "Choisir un déclencheur",
  triggerValueTitle: "Préciser la correspondance",
  actionTypeLabel: "Que doit faire Pace ?",
  nameSectionTitle: "Informations de la règle",
  sentencePending: "À définir",
  textMatchHint: "La correspondance ignore les majuscules et les espaces superflus.",
  categorySearch: "Rechercher une catégorie",
  noCategoryMatch: "Aucune catégorie ne correspond à votre recherche.",
};

const de: RulesUiLabels = {
  plans: "Pläne",
  title: "Regeln",
  subtitle: "Automatisieren Sie, wie Pace Ihre Transaktionen ordnet und behandelt.",
  searchLabel: "Regeln durchsuchen",
  searchPlaceholder: "Regeln durchsuchen…",
  statusFilter: "Status",
  statusALL: "Alle Status",
  statusACTIVE: "Aktiv",
  statusPAUSED: "Pausiert",
  statusARCHIVED: "Archiviert",
  newRule: "Neue Regel",
  kpiTotal: "Regeln gesamt",
  kpiActive: "Aktive Regeln",
  kpiApplied: "Diesen Monat angewendet",
  kpiReview: "Diesen Monat zur Prüfung gesendet",
  colRule: "Regel",
  colTrigger: "Auslöser",
  colAction: "Aktion",
  colStatus: "Status",
  colPriority: "Priorität",
  colApplied: "Angewendet",
  colLastApplied: "Zuletzt angewendet",
  appliedCount: "{count}× angewendet",
  neverApplied: "Noch nicht angewendet",
  loading: "Regeln werden aktualisiert…",
  emptyTitle: "Noch keine Regeln",
  emptyDescription:
    "Regeln kategorisieren neue Transaktionen automatisch oder senden sie zur Prüfung in Ihren Posteingang.",
  noResultsTitle: "Keine passenden Regeln",
  noResultsDescription: "Versuchen Sie eine andere Suche oder einen anderen Status.",
  clearFilters: "Filter zurücksetzen",
  details: "Regeldetails",
  trigger: "Auslöser",
  triggerEvent: "Wenn eine Transaktion erstellt wird",
  conditions: "Bedingungen",
  noConditions: "Keine weiteren Bedingungen",
  action: "Aktion",
  priority: "Priorität",
  created: "Erstellt",
  lastUpdated: "Zuletzt geändert",
  byYou: "{date} von Ihnen",
  byPace: "{date} von Pace",
  byMember: "{date} von einem Mitglied",
  recentExecutions: "Letzte Ausführungen",
  noExecutions: "Diese Regel wurde noch auf keine Transaktion angewendet.",
  back: "Zurück zu den Regeln",
  fieldTRANSACTION_KIND: "Transaktionsart",
  fieldENTRY_ORIGIN: "Quelle",
  fieldACCOUNT: "Konto",
  fieldCATEGORY: "Kategorie",
  fieldCOUNTERPARTY: "Händler",
  fieldNOTE: "Notiz",
  opEQUALS: "ist genau",
  opCONTAINS: "enthält",
  opSTARTS_WITH: "beginnt mit",
  opIS_EMPTY: "ist leer",
  opIS_NOT_EMPTY: "ist nicht leer",
  opIS_ONE_OF: "ist",
  opIS_NOT_ONE_OF: "ist nicht",
  kindEXPENSE: "Ausgabe",
  kindINCOME: "Einnahme",
  kindTRANSFER: "Überweisung",
  kindREFUND: "Erstattung",
  originMANUAL: "Manuelle Eingabe",
  originIMPORT: "Import",
  originAGENT: "Pace",
  originOTHER: "Sonstige",
  actionASSIGN_CATEGORY: "Kategorie festlegen",
  actionROUTE_FOR_REVIEW: "In den Posteingang senden",
  needsReview: "Prüfung nötig",
  unavailableReference: "Nicht verfügbar",
  unknownTransaction: "Transaktion",
  outcomeAPPLIED_ASSIGN_CATEGORY: "Kategorisiert",
  outcomeAPPLIED_ROUTE_FOR_REVIEW: "Zur Prüfung gesendet",
  outcomeSKIPPED: "Übersprungen",
  outcomeSHADOWED: "Überlagert",
  outcomeFAILED: "Fehlgeschlagen",
  outcomePENDING: "Ausstehend",
  enable: "Aktivieren",
  disable: "Deaktivieren",
  enabling: "Wird aktiviert…",
  disabling: "Wird deaktiviert…",
  more: "Weitere Aktionen",
  archive: "Archivieren",
  archiveTitle: "Diese Regel archivieren?",
  archiveDescription:
    "Die Regel wird nicht mehr auf neue Transaktionen angewendet. Ihr Verlauf bleibt erhalten und keine Transaktion wird geändert.",
  archiving: "Wird archiviert…",
  cancel: "Abbrechen",
  changed: "Diese Regel wurde geändert, seit Sie sie geöffnet haben.",
  reload: "Neueste Version laden",
  actionError: "Diese Regel konnte nicht aktualisiert werden. Bitte versuchen Sie es erneut.",
  errorTitle: "Regeln konnten nicht geladen werden",
  errorDescription: "Ihre Regeln konnten gerade nicht geladen werden. Bitte versuchen Sie es erneut.",
  retry: "Erneut versuchen",
  edit: "Bearbeiten",
  newRuleTitle: "Neue Regel erstellen",
  editRuleTitle: "Regel bearbeiten",
  builderSubtitleTRIGGER: "Wählen Sie, wann diese Regel greifen soll.",
  builderSubtitleCONDITIONS: "Fügen Sie Bedingungen hinzu, um Ihre Regel zu präzisieren.",
  builderSubtitleACTION: "Wählen Sie, was Pace tut, wenn die Regel zutrifft.",
  builderSubtitleREVIEW: "Prüfen Sie Ihre Regel und testen Sie sie vor dem Speichern an aktuellen Transaktionen.",
  stepper: "Regelschritte",
  stepProgress: "Schritt {current} von {total}",
  stepCompleted: "Abgeschlossen",
  stepCurrent: "Aktueller Schritt",
  stepTRIGGER: "Auslöser",
  stepHintTRIGGER: "Wann anwenden",
  stepCONDITIONS: "Bedingungen",
  stepHintCONDITIONS: "Treffer eingrenzen",
  stepACTION: "Aktion",
  stepHintACTION: "Was tun",
  stepREVIEW: "Prüfen",
  stepHintREVIEW: "Regel bestätigen",
  presetMERCHANT_CONTAINS: "Händler enthält",
  presetHintMERCHANT_CONTAINS: "Wenn der Händler- oder Quellname einen bestimmten Text enthält",
  presetMERCHANT_EQUALS: "Händler ist genau",
  presetHintMERCHANT_EQUALS: "Wenn der Händler- oder Quellname genau übereinstimmt",
  presetMERCHANT_EMPTY: "Händler ist leer",
  presetHintMERCHANT_EMPTY: "Wenn die Transaktion keinen Händler hat",
  presetACCOUNT_IS: "Konto ist",
  presetHintACCOUNT_IS: "Wenn die Transaktion von einem bestimmten Konto stammt",
  presetTRANSACTION_KIND_IS: "Transaktionsart",
  presetHintTRANSACTION_KIND_IS: "Wenn die Transaktion eine Ausgabe, Einnahme, Überweisung oder Erstattung ist",
  presetNOTE_CONTAINS: "Notiz enthält",
  presetHintNOTE_CONTAINS: "Wenn die Notiz der Transaktion einen bestimmten Text enthält",
  presetCATEGORY_EMPTY: "Ohne Kategorie",
  presetHintCATEGORY_EMPTY: "Wenn die Transaktion noch keine Kategorie hat",
  presetSOURCE_IS: "Quelle ist",
  presetHintSOURCE_IS: "Wenn die Transaktion manuell erfasst, importiert oder von Pace hinzugefügt wurde",
  triggerEventHint: "Regeln laufen auf neuen Transaktionen, nachdem sie erstellt wurden.",
  field: "Feld",
  operator: "Operator",
  value: "Wert",
  valuePlaceholder: "z. B. orange money",
  noOptions: "Keine Optionen verfügbar.",
  conditionsTitle: "Bedingungen festlegen (optional)",
  conditionNumber: "Bedingung {index}",
  removeCondition: "Bedingung {index} entfernen",
  addCondition: "Bedingung hinzufügen",
  noExtraConditions: "Keine weiteren Bedingungen. Die Regel greift, sobald der Auslöser zutrifft.",
  allConditionsHint: "Der Auslöser und alle Bedingungen müssen zutreffen.",
  actionTitle: "Aktion wählen",
  actionHintASSIGN_CATEGORY: "Unkategorisierten Ausgaben und Einnahmen eine Kategorie zuweisen",
  actionHintROUTE_FOR_REVIEW: "Die Transaktion zur Prüfung in Ihren Posteingang senden",
  category: "Kategorie",
  selectCategory: "Kategorie auswählen",
  noMoneyMovement: "Regeln bewegen nie Geld, erstellen keine Transaktionen und ändern keine Beträge.",
  reviewTitle: "Regel prüfen",
  ruleName: "Regelname",
  ruleNameHint: "Wird in Ihrer Regelliste angezeigt.",
  priorityHint: "1 läuft zuerst. Bei Konflikten gewinnt die kleinere Zahl.",
  priorityHighest: "{priority} (höchste)",
  enabledState: "Status",
  enabledOn: "Aktiviert – läuft auf neuen Transaktionen",
  enabledOff: "Deaktiviert – gespeichert, aber inaktiv",
  enableAfterSave: "Regel nach dem Speichern aktivieren",
  editEnabledHint: "Verwenden Sie Aktivieren oder Deaktivieren an der Regel, um den Status zu ändern.",
  dryRunTitle: "Regel testen",
  dryRunSubtitle: "Sehen Sie, wie diese Regel auf Ihre {count} neuesten Transaktionen wirken würde.",
  dryRunMatching: "Treffer ({count})",
  dryRunNotMatching: "Kein Treffer ({count})",
  dryRunRunning: "Regel wird getestet…",
  dryRunError: "Diese Regel konnte nicht getestet werden. Sie können sie trotzdem speichern.",
  dryRunRetry: "Erneut testen",
  dryRunEmptyMatching: "Keine aktuelle Transaktion trifft auf diese Regel zu.",
  dryRunEmptyNotMatching: "Alle aktuellen Transaktionen treffen auf diese Regel zu.",
  dryRunNoTransactions: "Noch keine aktuellen Transaktionen zum Testen.",
  dryRunNotice: "Dies ist eine Simulation. An Ihren Transaktionen wird nichts geändert.",
  dryRunDisabledNotice: "Diese Regel wird deaktiviert gespeichert und läuft erst, wenn Sie sie aktivieren.",
  dryRunWouldApply: "Würde greifen",
  dryRunSkipped: "Würde übersprungen",
  dryRunShadowed: "Überlagert von „{name}“",
  dryRunNoMatch: "Kein Treffer",
  whyMatched: "Warum sie zutrifft",
  whyNotMatched: "Warum sie nicht zutrifft",
  conditionMet: "Erfüllt",
  conditionNotMet: "Nicht erfüllt",
  transactionValue: "Transaktion: {value}",
  emptyValue: "leer",
  reasonTRANSACTION_KIND_NOT_SUPPORTED: "Nur Ausgaben und Einnahmen können kategorisiert oder geprüft werden",
  reasonTRANSACTION_LOCKED: "Diese Transaktion kann nicht mehr bearbeitet werden",
  reasonCATEGORY_ALREADY_SET: "Hat bereits eine Kategorie",
  reasonCATEGORY_UNAVAILABLE: "Kategorie nicht verfügbar",
  reasonCATEGORY_KIND_MISMATCH: "Kategorie passt nicht zu dieser Transaktionsart",
  reasonALREADY_IN_REVIEW: "Bereits in Ihrem Posteingang",
  reasonSHADOWED_BY_HIGHER_PRIORITY_RULE: "Eine Regel mit höherer Priorität greift zuerst",
  reasonACTION_FAILED: "Aktion fehlgeschlagen",
  continue: "Weiter",
  backStep: "Zurück",
  createRule: "Regel erstellen",
  saveChanges: "Änderungen speichern",
  saving: "Wird gespeichert…",
  close: "Schließen",
  fixErrors: "Korrigieren Sie die markierten Felder, um fortzufahren.",
  errorVALUE_REQUIRED: "Geben Sie einen Wert ein.",
  errorSELECTION_REQUIRED: "Wählen Sie mindestens eine Option.",
  errorTEXT_TOO_LONG: "Verwenden Sie höchstens 160 Zeichen.",
  errorTOO_MANY_VALUES: "Wählen Sie höchstens 50 Optionen.",
  errorTOO_MANY_CONDITIONS: "Sie können bis zu 10 Bedingungen verwenden.",
  errorCATEGORY_REQUIRED: "Wählen Sie eine Kategorie.",
  errorNAME_REQUIRED: "Geben Sie dieser Regel einen Namen.",
  errorNAME_TOO_LONG: "Verwenden Sie höchstens 160 Zeichen.",
  errorPRIORITY_INVALID: "Geben Sie eine ganze Zahl von 1 bis 10.000 ein.",
  saveError: "Diese Regel konnte nicht gespeichert werden. Bitte versuchen Sie es erneut.",
  saveInvalid: "Einige Regeldetails sind nicht mehr gültig. Prüfen Sie Kategorie und Konten.",
  staleEdit: "Diese Regel wurde geändert, seit Sie sie geöffnet haben. Ihre Änderungen wurden nicht gespeichert.",
  previewLabel: "Regelvorschau",
  selectValues: "Eine oder mehrere auswählen",
  searchOptions: "Suchen…",
  triggerOptionsTitle: "Auslöser wählen",
  triggerValueTitle: "Treffer präzisieren",
  actionTypeLabel: "Was soll Pace tun?",
  nameSectionTitle: "Regeldetails",
  sentencePending: "Noch offen",
  textMatchHint: "Groß-/Kleinschreibung und zusätzliche Leerzeichen werden ignoriert.",
  categorySearch: "Kategorien suchen",
  noCategoryMatch: "Keine Kategorie passt zu Ihrer Suche.",
};

const rulesLabels: Readonly<Record<DashboardLanguage, RulesUiLabels>> = { en, fr, de };

export function getRulesUiLabels(language: DashboardLanguage): RulesUiLabels {
  return rulesLabels[language];
}
